/*
 FusionCharts JavaScript Library - KDtree
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.12.0
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.12.0
*/
(function(T){"object"===typeof module&&"undefined"!==typeof module.exports?module.exports=T:T(FusionCharts)})(function(T){T.register("module",["private","modules.renderer.js-kdtree",function(){function q(g){function m(g,p,z,q){var I={},A;A=q?"y":"x";if(p===z)return I.point=g[p],I;if(1===z-p)return g[p][A]>g[z][A]?(I.point=g[p],I.left={point:g[z]}):(I.point=g[z],I.left={point:g[p]}),I;A=p+z>>1;q?u(g,A,p,z):J(g,A,p,z);I.point=g[A];I.left=m(g,p,A-1,!q);I.right=m(g,A+1,z,!q);return I}function J(g,m,z,
q){for(var w,A,u,B,C;q>z;){600<q-z&&(w=q-z+1,A=m-z+1,u=E(w),B=.5*H(2*u/3),C=.5*N(u*B*(w-B)/w)*(0>A-w/2?-1:1),u=y(z,L(m-A*B/w+C)),w=F(q,L(m+(w-A)*B/w+C)),J(g,m,u,w));w=g[m];A=z;B=q;p(g,z,m);for(g[q].x>w.x&&p(g,z,q);A<B;){p(g,A,B);A++;for(B--;g[A].x<w.x;)A++;for(;g[B].x>w.x;)B--}g[z].x===w.x?p(g,z,B):(B++,p(g,B,q));B<=m&&(z=B+1);m<=B&&(q=B-1)}}function u(g,m,z,w){for(var q,A,J,B,C;w>z;){600<w-z&&(q=w-z+1,A=m-z+1,J=E(q),B=.5*H(2*J/3),C=.5*N(J*B*(q-B)/q)*(0>A-q/2?-1:1),J=y(z,L(m-A*B/q+C)),q=F(w,L(m+(q-
A)*B/q+C)),u(g,m,J,q));q=g[m];A=z;B=w;p(g,z,m);for(g[w].y>q.y&&p(g,z,w);A<B;){p(g,A,B);A++;for(B--;g[A].y<q.y;)A++;for(;g[B].y>q.y;)B--}g[z].y===q.y?p(g,z,B):(B++,p(g,B,w));B<=m&&(z=B+1);m<=B&&(w=B-1)}}function p(g,m,z){var q=g[m];g[m]=g[z];g[z]=q}var C=g&&g[0]&&g[0].r||5,q,y=Math.max,L=Math.floor,N=Math.sqrt,F=Math.min,E=Math.log,H=Math.exp,G=Math.pow;g=g||[];for(q=g.length;q--;)g[q].r>C&&(C=g[q].r),g[q].i=q,g[q].x=+g[q].x,g[q].y=+g[q].y;return{tree:0===g.length?{}:m(g,0,g.length-1,!1),search:function(g,
m,z){function q(a,b){return"circle"===z?N(G(a-g,2)+G(b-m,2))<=y:a>=y&&a<=F&&b>=E&&b<=H}function w(a){var c=g>=a.x1&&g<=a.x2&&m>=a.y1&&m<=a.y2,d;d=a.point.y;d=N(G(g-a.point.x,2)+G(m-d,2));P?c?e?a.point.i>P.point.i&&(P=a,e=c,b=d):(P=a,e=c,b=d):!e&&d<b&&(P=a,e=c,b=d):(P=a,e=c,b=d)}function p(a){"circle"===z?y=a:(y=g-a||0,F=g+a||0,E=m-a||0,H=m+a||0)}function J(a){a&&a.point&&(p(a.point.r),q(a.point.x,a.point.y)&&w(a),y<=a.point.x&&u(a.left),F>=a.point.x&&u(a.right))}function u(a){a&&a.point&&(p(a.point.r),
q(a.point.x,a.point.y)&&w(a),E<=a.point.y&&J(a.left),H>=a.point.y&&J(a.right))}var P,y=g-C,F=g+C,E=m-C,H=m+C,e=!1,b=0;J(this.tree);return P&&P.point||P}}}function R(g){this.configure(g)}var u=this.hcLib,S=function(g,m,q,u,p){return Math.pow(q-g,2)+Math.pow(u-m,2)<=Math.pow(p,2)},T=Math.PI,U=Math.cos,g=Math.sin,Q=Math.max,y=Math.min,X=T/180,m=function(g,m,q,u,p,C){return q<=Q(g,p)&&q>=y(g,p)&&u<=Q(m,C)&&u>=y(m,C)?!0:!1},W=function(g,m,q,u,p,C){m=(u-m)*(p-q);g=(q-g)*(C-u);isNaN(m)&&(m=0);isNaN(g)&&
(g=0);g=m-g;return 0===g?0:0<g?1:2};R.prototype={configure:function(g){this.validatorFn=g?this.shapeValidator():this.defaultValidator()},defaultValidator:function(){var g=this;return function(m){var q=g.mousePoint;return m&&1>=Math.pow((m.x-q.x)/g.xLimit,2)+Math.pow((m.y-q.y)/g.yLimit,2)?!0:!1}},shapeValidator:function(){var q=this;return function(w){var u=q.mousePoint,y=w&&w.shapeInfo,p=!1,C,O=u.x,u=u.y,M;switch(y&&y.type){case "circle":C=y.radius;p=S(O,u,w.x,w.y,C);break;case "arc":p=y.innerradius;
C=y.radius;p=!S(O,u,w.x,w.y,p)&&S(O,u,w.x,w.y,C);break;case "polygon":C=y.radius;M=y.startAngle;y=y.sides;a:{p=w.x;w=w.y;var L,N=0,F,E,H,G,R;L=!1;if(S(O,u,p,w,C)&&3<=y){L=void 0===M?.5*T:M%360*X;R=2*T/y;F=p+C*U(-L);G=w+C*g(-L);for(M=0;M<y;M++){L+=R;E=p+C*U(-L);H=w+C*g(-L);var Q=F,V=G,Y=E,I=H,A=O,Z=u,B=u,K=W(Q,V,Y,I,A,Z),ba=W(Q,V,Y,I,Infinity,B),da=W(A,Z,Infinity,B,Q,V),ca=W(A,Z,Infinity,B,Y,I);if(K!==ba&&da!==ca||0===K&&m(Q,V,A,Z,Y,I)||0===ba&&m(Q,V,Infinity,B,Y,I)||0===da&&m(A,Z,Q,V,Infinity,B)||
0===ca&&m(A,Z,Y,I,Infinity,B)){if(0===W(F,G,O,u,E,H)){p=m(F,G,O,u,E,H);break a}N++}F=E;G=H}L=0!==N%2}p=L}break;case "rect":p=w.x;C=w.y;w=p+(y.width||0);y=C+(y.height||0);p=O>=p&&O<=w&&u>=C&&u<=y;break;case "default":p=!1}return p}},buildKdTree:function(g){this.kdTree=q(g);this.tree=this.kdTree.tree;return this},getNeighbour:function(g,m,q){var u=this.tree,p={x1:g.x-this.xLimit,x2:g.x+this.xLimit,y1:g.y-this.yLimit,y2:g.y+this.yLimit},y=this.validatorFn;this.mousePoint=g;if(m)return this.kdTree&&this.kdTree.search(g.x,
g.y,q);if(u)return this._searchBtwnLimit(p,u,!0,y)},_compair2closest:function(g,m){return!g||g&&m&&m.i>g.i?m:g},_searchBtwnLimit:function(g,m,q,u){var p,y,O=q?g.x1:g.y1,M=q?g.x2:g.y2;p=m&&m.point&&m.point[q?"x":"y"];if(void 0!==p)return u(m.point)&&(y=m.point),p>=O&&m.left&&(y=this._compair2closest(y,this._searchBtwnLimit(g,m.left,!q,u))),p<=M&&m.right&&(y=this._compair2closest(y,this._searchBtwnLimit(g,m.right,!q,u))),y},_setSearchLimit:function(g,m){this.xLimit=g;this.yLimit=m}};R.prototype.constructor=
R;u.KdTree=R}]);T.register("module",["private","modules.renderer.js-gradientlegend",function(){function q(e,b){(function c(b,h){var k,f;for(f in b)da.call(b,f)&&(k=b[f],void 0===h[f]?h[f]=k:"object"===typeof k&&c(k,h[f]))})(e,b);return b}function R(e){return Z(e?e:ba)||ba}function u(e){var b=e.fontSize+"";if(!b)return e;b=b.replace(/(\d+)(px)*/,"$1px");e.fontSize=b;return e}function S(e){return void 0===e||"undefined"===typeof e||null===e||e!==e?!0:!1}function aa(e,b){this.carpet=e;this._componentPool=
b}function U(e){this.conf=e;this._id="GL_CARPET";this.compositionsByCategory={};this._lSpace=this.group=this.node=void 0;this.autoRecalculate=!1;this.groupName="fc-gradient-legend";this.moveInstructions={}}function g(){U.apply(this,arguments)}function Q(e,b){this.rawText=e;this.conf=b;this._id="GL_CAPTION";this._lSpace=this.bound=this.node=void 0}function y(e,b,a){this.colorRange=e;this.conf=b;this.childTextConf=a;this._id="GL_BODY";this.bound=void 0;this.compositionsByCategory={};this._lSpace=void 0}
function X(){y.apply(this,arguments)}function m(e){this.conf=e;this._id="GL_LABELS"}function W(){m.apply(this,arguments)}function z(){m.apply(this,arguments);this._id="GL_VALUES"}function w(){z.apply(this,arguments);this._id="GL_VALUES"}function J(e){this.conf=e;this._id="FL_AXIS";this.markerLine=this.shadow=this.node=void 0;this.compositionsByCategory={}}function P(){J.apply(this,arguments)}function p(e){var b={};this._id="GL_SG1";this.conf=e;b.conf=e;this.extremes=[];this.sliders={};b.sliderGroup=
this;this.valueRange=[];this.callbacks=[];this.sliders[!1]=new C(!1,b,this._id+"_0");this.sliders[!0]=new C(!0,b,this._id+"_1")}function C(e,b,a){this.conf=b.conf;this.sliderIndex=e;this.rangeGroup=b.sliderGroup;this._id=a;this.tracker=this.node=void 0;this.currPos=0;this.swing=[]}function O(e,b,a){a=a.components.numberFormatter;var c,d,h,k,f,l;this.data=e;this.options=b||{};l=this.mapByPercent=!!e.mapByPercent;this.appender="";d=this.mapByPercent?0:b.min;b=this.mapByPercent?100:b.max;2===e.colorRange.length&&
(c=e.colorRange[0],h=e.colorRange[1],k=c.value=S(c.value)?d:c.value,f=h.value=S(h.value)?b:h.value,k===f&&(k=c.value=d,f=h.value=b),c.displayValue=l?k+"%":a.legendValue(k),h.displayValue=l?f+"%":a.legendValue(f));S(d)&&S(c.value)||S(b)&&S(c.value)||!e.gradient?this._preparationGoneWrong=!0:this._preparationGoneWrong=!1;a=this.colorRange=e.colorRange.sort(function(a,b){return a.value-b.value});this.valueRatio=void 0;this.values=[];e=0;for(c=a.length;e<c;e++)this.values.push(a[e].value)}function M(){aa.apply(this,
arguments)}var L=this,N=L.hcLib,F=N.pluckNumber,E=N.pluck,H=N.toRaphaelColor,G=N.graphics,fa=N.dehashify,ga=N.hashify,V=G.convertColor,Y=G.RGBtoHex,I=G.HEXtoRGB,A=G.getLightColor,Z=G.getValidColor,B="rgba(192,192,192,"+(N.isIE?.002:1E-6)+")",K,ba=N.COLOR_BLACK,da={}.hasOwnProperty,ca,ea={};K=function(){function e(a){var c=b.numberFormatter,k,f,l;k=0;for(f=a.length;k<f;k++)if(l=a[k].maxvalue)a[k].maxvalue=c.getCleanValue(l)}var b,a,c={legendCarpetConf:{spreadFactor:.85,allowDrag:!1,captionAlignment:"center",
padding:{v:3,h:3},style:{fill:"#e4d9c1",stroke:"#c4b89d"}},legendCaptionConf:{spreadFactor:.2,padding:{v:2,h:2},style:{fill:"#786B50",fontFamily:"sans-serif",fontSize:"12px",fontWeight:"bold",fontStyle:"normal"},bound:{style:{stroke:"none"}}},legendBodyConf:{spreadFactor:.8,padding:{v:2,h:2},bound:{style:{stroke:"none"}}}};c.legendAxisConf={legendAxisHeight:11,spreadFactor:.4,padding:{v:1,h:1},style:{stroke:"none","stroke-opacity":0,"stroke-width":1},line:{grooveLength:3,offset:8,style:{stroke:"rgba(255, 255, 255, 0.65)",
"stroke-width":1.5}},shadow:{style:{stroke:"none",fill:H({FCcolor:{alpha:"25,0,0",angle:360,color:"000000,FFFFFF,FFFFFF",ratio:"0,30,40"}})}},bound:{style:{stroke:"none"}}};c.sliderGroupConf={showTooltip:1,outerCircle:{rFactor:1.4,style:{fill:B,stroke:"#757575","stroke-width":3}},innerCircle:{rFactor:.65,style:{fill:B,stroke:"#FFFFFF"}}};c.axisTextItemConf={spreadFactor:.3,padding:{v:1,h:1},style:{fill:"#786B50",fontFamily:"sans-serif",fontSize:"12px",fontWeight:"normal",fontStyle:"normal"}};return{init:function(c){a=
c.chart;b=a.components},setConf:function(a){},legacyDataParser:function(a,c){var k={},f=b.numberFormatter,l,r,n,D,g,m,t,v,q;if(!a)return!1;k.mapByPercent=q=!!F(a.mapbypercent,0);l=a.color||[];void 0===a.minvalue&&(a.minvalue=void 0!==c.min?q?0:c.min:0);void 0===a.maxvalue&&(a.maxvalue=void 0!==c.max?q?100:c.max:100);m=!1;n=0;for(D=l.length;n<D;n++)if(l[n].maxvalue){m=!0;break}m||(l=[]);n=a.code;m=k.colorRange=[];k.gradient=!!F(a.gradient,1);l.length?n=R(n):(n?(D=R(n),n=R()):(n=R(),D=A(n,1)),l.push({code:D,
maxvalue:a.maxvalue,label:void 0}));e(l);l=l.sort(function(a,b){return a.maxvalue-b.maxvalue});t=v=a.minvalue&&f.getCleanValue(a.minvalue);v=(void 0!==t||null!==t)&&(q?t+"%":f.legendValue(t));m.push({code:fa(n),value:t,displayValue:v,label:a.startlabel});n=0;for(D=l.length;n<D;n++)r=l[n],g=R(r.code||r.color),t=v=r.maxvalue,isNaN(parseInt(t,10))||(v=(void 0!==t||null!==t)&&(q?t+"%":f.legendValue(t)),m.push(Object({code:fa(g),value:t,displayValue:v,label:r.label||r.displayvalue})));m[m.length-1].label=
a.endlabel||r.label;return k},getDefaultConf:function(a){return c[a]}}}();ca=function(e){var b=e.chartInstance.id,a=ea[b]||(ea[b]={});return function(){function c(){var b,c,d,h,k,e;for(b in a)for(c in d=a[b],d)if(h=d[c],h instanceof Array)for(k=0,e=h.length;k<e;k++)h[k]&&h[k].hide();else h.hide()}var d,h={},k;d={KEY_RECT:"rect",KEY_TEXT:"text",KEY_GROUP:"group",KEY_CIRCLE:"circle",KEY_PATH:"path"};h[d.KEY_RECT]=function(a){return k.rect(a)};h[d.KEY_TEXT]=function(a,b){return k.text(a,b)};h[d.KEY_GROUP]=
function(a,b){return k.group(a,b)};h[d.KEY_CIRCLE]=function(a){return k.circle(a)};h[d.KEY_PATH]=function(a,b){return k.path(a,b)};return{init:function(a){k=a;c()},emptyPool:function(){a=ea[b]={}},getChart:function(){return e},getComponent:function(b,c,d){var k=a[b],e,g,m,t=0;k||(k=a[b]={});return(g=k[c])&&!(g instanceof Array)||g instanceof Array&&0<g.length?function(){return d?(m=g[t++])?m.show():g[t]=h[c].apply(this,arguments):g.show()}:function(){return d?(e=k[c]||(k[c]=[]),g=h[c].apply(this,
arguments),e.push(g),g.show()):k[c]=h[c].apply(this,arguments)}},hideAll:function(){c()},getKeys:function(){return d}}}()};aa.prototype.constructor=aa;aa.prototype.draw=function(e){e.componentPool=this._componentPool;return this.carpet.draw(e)};aa.prototype.getLogicalSpace=function(e,b){e.componentPool=this._componentPool;return this.carpet.getLogicalSpace(e,b)};aa.prototype.dispose=function(){this.carpet&&this.carpet.group&&this.carpet.group.remove();this._componentPool.emptyPool()};U.prototype.constructor=
U;U.prototype.addCompositions=function(e,b){this.compositionsByCategory[b]=e};U.prototype.getBoundingBox=function(e){var b=this.conf,a=e.refSide,c=e.alignment,d=e.refOffset,h=e.x,k=e.y,b=b.width=a*b.spreadFactor;!c||void 0!==h&&null!==h||(h=(d+a)/2-b/2);return{width:b,height:e.maxOtherSide,x:h,y:k}};U.prototype.getPostCalcDecisions=function(e,b){var a=this.conf.padding,c,d=0;for(c in b)d+=b[c].height||0;e.height=d+2*a.v};U.prototype.getLogicalSpace=function(e,b){var a=this._lSpace,c=this.conf.padding,
d=this.compositionsByCategory,h,k,f;f=0;var l={},r,n=0;if(a&&!b)return a.isImpure=!0,a;a=this._lSpace=k=this.getBoundingBox(e);if(S(a.x)||S(a.y)||S(a.height)||S(a.width))this.autoRecalculate=!0;a=q(k,{});a.height-=2*c.v;a.width-=2*c.h;a.x+=c.h;a.y+=c.v;for(r in d)h=d[r],c=q(a,{}),c.y+=f,f=a.height*h.conf.spreadFactor,c.height=f+n,f=h.getLogicalSpace(q(c,{}),e,b),n=c.height-f.height,l[r]=f,f=f.height;this.getPostCalcDecisions(k,l);return this._lSpace=k};U.prototype.setupDragging=function(){var e=this.group,
b=0,a=0,c=0,d=0;e.css({cursor:"move"});e.drag(function(h,k){b=h;a=k;e.attr({transform:"t"+(c+b)+","+(d+a)})},function(){c+=b;d+=a},function(){})};U.prototype.draw=function(e){var b=this.conf,a=this.compositionsByCategory,c=e.paper,d=e.parentGroup,h=e.componentPool,k,f,l=h.getChart().get("config","animationObj").duration,r,n=h.getKeys();this.getLogicalSpace(e,this.autoRecalculate);f=this._lSpace;r=h.getComponent(this._id,n.KEY_GROUP);this.group=d=r(this.groupName,d);d.attr({opacity:0});d.animate({opacity:1},
l,"easeIn");r=h.getComponent(this._id,n.KEY_RECT);this.node=r(d).attr(f).css(b.style);for(k in a)h=a[k],h.draw(b.captionAlignment,f,{colorRange:e.colorRange,numberFormatter:e.numberFormatter,paper:c,parentLayer:d,smartLabel:e.smartLabel,moveInstructions:this.moveInstructions[k],componentPool:e.componentPool});b.allowDrag&&this.setupDragging();return this.node};g.prototype=Object.create(U.prototype);g.prototype.constructor=g;g.prototype.getBoundingBox=function(e){var b=this.conf,a=e.refSide,c=e.alignment,
d=e.refOffset,h=e.x,k=e.y,b=b.height=a*b.spreadFactor;!c||void 0!==k&&null!==k||(k=(d+a)/2-b/2);return{width:e.maxOtherSide,height:b,x:h,y:k}};g.prototype.getPostCalcDecisions=function(e,b){var a=this.conf.padding,c=Number.NEGATIVE_INFINITY,d,h,k=this.moveInstructions;U.prototype.getPostCalcDecisions.apply(this,arguments);for(h in b)d=b[h].width,c=c<d?d:c;e.width=c+2*a.h;for(h in b)if(d=b[h].width,a=c-d)k[h]="t"+a/2+",0"};Q.prototype.constructor=Q;Q.LEFT={x:function(e,b){return b.x+e.width/2+2}};
Q.RIGHT={x:function(e,b){return b.x+b.width-e.width/2-2}};Q.CENTER={x:function(e,b){return b.x+b.width/2}};Q.prototype.getLogicalSpace=function(e,b,a){var c=this.conf.padding,d=this._lSpace,h=this.rawText,k=b.componentPool.getChart();if(d&&!a)return d.isImpure=!0,d;d=this._lSpace={bound:{height:0,width:0},node:{logicArea:void 0,smartText:void 0}};a=b.smartLabel;if(!h)return d.bound;b=q(e,{});b.height-=2*c.v;b.width-=2*c.h;b.x+=c.h;b.y+=c.v;a.useEllipsesOnOverflow(k.config.useEllipsesWhenOverflow);
k=q(this.conf.style,{});u(k);a.setStyle(this._metaStyle=k);h=a.getSmartText(h,b.width,b.height);b.height=h.height;b.width=h.width;e.height=h.height+2*c.v;e.width=h.width+2*c.h;d.node.smartText=h;d.node.logicArea=b;return d.bound=e};Q.prototype.draw=function(){var e=this.conf,b,a=e.bound||{},c,d,h,k,f,l,r;3<=arguments.length?(h=arguments[0],k=arguments[1],f=arguments[2]):2<=arguments.length&&(h=arguments[0],f=arguments[1]);b=f.parentLayer;l=f.componentPool;r=l.getKeys();c=l.getComponent(this._id,r.KEY_GROUP);
this.group=b=c("legend-caption",b).css(e.style);this.getLogicalSpace(k,f);c=this._lSpace;f=c.node;d=c.bound;c=l.getComponent(this._id,r.KEY_RECT);this.bound=a=c(b).attr(d).css(a.style);h="string"===typeof h?Q[h.toUpperCase()].x(f.smartText,k||f.logicArea):h;c=l.getComponent(this._id,r.KEY_TEXT);this.node=c({},b).attr({text:f.smartText.text,x:h,y:f.logicArea.y+f.smartText.height/2,lineHeight:this._metaStyle.lineHeight,fill:e.style.fill});return{group:b,bound:a,node:this.node}};y.SC_STACK=["LEGEND_LABEL",
"LEGEND_AXIS","AXIS_VALUE"];y.DARW_STACK=["AXIS_VALUE","LEGEND_AXIS","LEGEND_LABEL"];y.prototype.constructor=y;y.prototype.addCompositions=function(e,b){this.compositionsByCategory[b]=e};y.prototype.getCompositionPlotAreaFor=function(e){var b;b=q(e,{});return function(a,c){a=a||{};b.y+=a.height||0;b.height=e.height*c;return b}};y.prototype.getSpaceTaken=function(e){return e.height};y.prototype.updateEffectivePlotArea=function(e,b,a){var c=this.conf.padding;b.height=a;e.height=a+2*c.v};y.prototype.getLogicalSpace=
function(e,b,a){var c=this._lSpace,d=this.conf.padding,h=this.compositionsByCategory,k,f,l,r=0,n,D;if(c&&!a)return c.isImpure=!0,c;c=this._lSpace={bound:{height:0,width:0},node:{logicArea:void 0}};f=q(e,{});f.height-=2*d.v;f.width-=2*d.h;f.x+=d.h;f.y+=d.v;l=this.getCompositionPlotAreaFor(f);b.colorRange=this.colorRange;n=0;for(D=y.SC_STACK.length;n<D;n++)if(d=h[y.SC_STACK[n]])k=l(k,d.conf.spreadFactor),k=d.getLogicalSpace(q(k,{}),b,a),r+=this.getSpaceTaken(k);this.updateEffectivePlotArea(e,f,r);c.node.logicArea=
f;return c.bound=e};y.prototype.draw=function(){var e=this.childTextConf,b=this.conf.bound.style||{},a=this.compositionsByCategory,c,d,h,k,f,l,r;3<=arguments.length?(h=arguments[1],f=arguments[2]):2<=arguments.length&&(f=arguments[1]);c=f.parentLayer;k=f.componentPool;l=k.getKeys();this.getLogicalSpace(h,f);h=this._lSpace;r=k.getComponent(this._id,l.KEY_GROUP);e=r("legend-body",c).attr({transform:"t0,0"}).css(e.style);r=k.getComponent(this._id,l.KEY_RECT);this.bound=b=r(e).attr(h.bound).css(b);f.colorRange=
this.colorRange;f.parentLayer=e;k=0;for(l=y.DARW_STACK.length;k<l;k++)(d=a[y.DARW_STACK[k]])&&d.draw(f);f.moveInstructions&&e.attr({transform:f.moveInstructions});return{bound:b,group:e}};X.prototype=Object.create(y.prototype);X.prototype.constructor=X;X.prototype.getCompositionPlotAreaFor=function(e){var b;b=q(e,{});return function(a,c){a=a||{};b.x+=a.width||0;b.width=e.width*c;return b}};X.prototype.updateEffectivePlotArea=function(e,b,a){var c=this.conf.padding;b.width=a;e.width=a+2*c.h};X.prototype.getSpaceTaken=
function(e){return e.width};m.prototype.constructor=m;m.prototype.getEffectivePlotArea=function(e){var b=this.conf.padding;e.height-=2*b.v;e.width-=2*b.h;e.x+=b.h;e.y+=b.v;this.node=[];return e};m.prototype.getLogicalSpace=function(e,b,a){var c=this._lSpace,d=this.conf,h=d.padding,k,f,l=[],r,n,D,g,m,t=0,v,ha,y;m=b.componentPool.getChart();var p=[];if(c&&!a)return c.isImpure=!0,c;c=b.colorRange;b=b.smartLabel;a=c.getCumulativeValueRatio();k=c.colorRange;c=this._lSpace={bound:{height:0,width:0},node:{logicArea:void 0,
smartTexts:[]}};g=c.node.smartTexts;r=q(e,{});r=this.getEffectivePlotArea(r);b.useEllipsesOnOverflow(m.config.useEllipsesWhenOverflow);d=q(d.style,{});u(this._metaStyle=d);b.setStyle(d);m=b.getSmartText("W");f=0;for(d=k.length;f<d;f++)(n=k[f].label)?(t++,p.push({oriIndex:f,label:n})):g[f]=void 0;d=p.length;if(0===d)return{height:0,width:0};n=D=1<d?(a[p[d-1].oriIndex]-a[p[0].oriIndex])/2*r.width/100:Math.max(a[p[0].oriIndex],100-a[p[0].oriIndex])/2*r.width/100;t=b.getSmartText(p[0].label,n,r.height);
t.x=a[p[0].oriIndex]*r.width/100;f=t.x+t.width;l.push(t.height);g[p[0].oriIndex]=t;t=b.getSmartText(p[d-1].label,n,r.height);t.x=a[p[d-1].oriIndex]*r.width/100;k=t.x-t.width;l.push(t.height);g[p[d-1].oriIndex]=t;ha=f;for(f=1;f<d-1;f++)n=p[f].label,y=p[f].oriIndex,t=void 0,D=f+1===d-1?k:a[p[f+1].oriIndex]*r.width/100,v=a[p[f].oriIndex]*r.width/100,D=Math.min(v-ha,D-v),D>2*m.width&&(t=b.getSmartText(n,D,r.height),t.x=a[y]*r.width/100,ha=D,l.push(t.height)),g[p[f].oriIndex]=t;l=Math.max.apply(Math,l);
r.height=l;e.height=l+2*h.v;c.node.logicArea=r;return c.bound=e};m.prototype.draw=function(){var e,b,a=this.conf;b=a.bound&&a.bound.style||{stroke:"none"};var c,d,h,k,f,l,r,n;2<=arguments.length?(d=arguments[0],k=arguments[1]):1<=arguments.length&&(k=arguments[0]);e=k.parentLayer;k.colorRange.getCumulativeValueRatio();c=k.componentPool;f=c.getKeys();this.getLogicalSpace(d,k);h=this._lSpace;d=h.node.logicArea;k=h.node.smartTexts;n=c.getComponent(this._id,f.KEY_GROUP);e=n("legend-labels",e);n=c.getComponent(this._id,
f.KEY_RECT);this.bound=b=n(e).attr(h.bound).css(b);n=c.getComponent(this._id,f.KEY_TEXT,!0);f=0;for(h=k.length;f<h;f++)if(c=k[f])l=d.y+c.height/2,r=f===h-1?d.x+c.x-c.width/2:f?d.x+c.x:d.x+c.x+c.width/2,this.node.push(n({},e).attr({text:c.text,x:r,y:l,lineHeight:this._metaStyle.lineHeight,fill:a.style.fill}).transform("R0"));return{group:e,bound:b,node:this.node}};W.prototype=Object.create(m.prototype);W.prototype.constructor=W;W.prototype.getLogicalSpace=function(e,b,a){var c=this._lSpace,d=this.conf,
h=d.padding,k,f,l=[],r,n,g,m,x,t=0,v,p,y;x=b.componentPool.getChart();var w=[];if(c&&!a)return c.isImpure=!0,c;c=b.colorRange;b=b.smartLabel;a=c.getCumulativeValueRatio();k=c.colorRange;c=this._lSpace={bound:{height:0,width:0},node:{logicArea:void 0,smartTexts:[]}};m=c.node.smartTexts;r=q(e,{});r=this.getEffectivePlotArea(r);b.useEllipsesOnOverflow(x.config.useEllipsesWhenOverflow);d=q(d.style,{});u(this._metaStyle=d);b.setStyle(d);x=b.getSmartText("W");f=0;for(d=k.length;f<d;f++)(n=k[f].label)?(t++,
w.push({oriIndex:f,label:n})):m[f]=void 0;d=w.length;if(0===d)return{height:0,width:0};n=g=1<d?(a[w[d-1].oriIndex]-a[w[0].oriIndex])/2*r.height/100:Math.max(a[w[0].oriIndex],100-a[w[0].oriIndex])/2*r.height/100;t=b.getSmartText(w[0].label,n,r.width);t.y=a[w[0].oriIndex]*r.height/100;f=t.y+t.width;l.push(t.height);m[w[0].oriIndex]=t;t=b.getSmartText(w[d-1].label,n,r.width);t.y=a[w[d-1].oriIndex]*r.height/100;k=t.y-t.width;l.push(t.height);m[w[d-1].oriIndex]=t;p=f;for(f=1;f<d-1;f++)n=w[f].label,y=w[f].oriIndex,
t=void 0,g=f+1===d-1?k:a[w[f+1].oriIndex]*r.height/100,v=a[w[f].oriIndex]*r.height/100,g=Math.min(v-p,g-v),g>2*x.width&&(t=b.getSmartText(n,g,r.width),t.y=a[y]*r.height/100,p=g,l.push(t.height)),m[w[f].oriIndex]=t;l=Math.max.apply(Math,l);r.width=l;e.width=l+2*h.v;c.node.logicArea=r;return c.bound=e};W.prototype.draw=function(){var e,b,a=this.conf;b=a.bound&&a.bound.style||{stroke:"none"};var c,d,h,k,f,l,r,n;2<=arguments.length?(d=arguments[0],k=arguments[1]):1<=arguments.length&&(k=arguments[0]);
e=k.parentLayer;k.colorRange.getCumulativeValueRatio();c=k.componentPool;f=c.getKeys();this.getLogicalSpace(d,k);h=this._lSpace;d=h.node.logicArea;k=h.node.smartTexts;n=c.getComponent(this._id,f.KEY_GROUP);e=n("legend-labels",e);n=c.getComponent(this._id,f.KEY_RECT);this.bound=b=n(e).attr(h.bound).css(b);n=c.getComponent(this._id,f.KEY_TEXT,!0);f=0;for(h=k.length;f<h;f++)if(c=k[f])l=d.x+c.height/2,r=f===h-1?d.y+c.y-c.width/2:f?d.y+c.y:d.y+c.y+c.width/2,this.node.push(n({},e).attr({text:c.text,x:l,
y:r,lineHeight:this._metaStyle.lineHeight,fill:a.style.fill}).transform("R270,"+l+","+r));return{group:e,bound:b,node:this.node}};z.prototype=Object.create(m.prototype);z.prototype.constructor=z;z.prototype.getLogicalSpace=function(e,b,a){var c=this._lSpace,d=this.conf,h=d.padding,k=b.componentPool.getChart(),f,l,r,n,g,m,x=[],t,v,p,y;if(c&&!a)return c.isImpure=!0,c;c=b.colorRange;b=b.smartLabel;a=c.colorRange;r=c.getCumulativeValueRatio();c=this._lSpace={bound:{height:0,width:0},node:{logicArea:void 0,
smartTexts:[]}};y=c.node.smartTexts;v=q(e,{});v.height-=2*h.v;v.width-=2*h.h;v.x+=h.h;v.y+=h.v;b.useEllipsesOnOverflow(k.config.useEllipsesWhenOverflow);d=q(d.style,{});u(this._metaStyle=d);b.setStyle(d);k=b.getSmartText("W");d=a.length;m=(r[d-1]-r[0])/2*v.width/100;f=a[0].displayValue;f=b.getSmartText("string"!==typeof f&&void 0!==f&&f.toString()||f,m,v.height);f.x=r[0]*v.width/100;l=f.x+f.width;x.push(f.height);y[0]=f;f=b.getSmartText(a[d-1].displayValue,m,v.height);f.x=r[d-1]*v.width/100;m=f.x-
f.width;x.push(f.height);y[d-1]=f;t=l;for(l=1;l<d-1;l++)f=void 0,p=a[l].displayValue,n=l+1===d-1?m:r[l+1]*v.width/100,g=r[l]*v.width/100,n=Math.min(g-t,n-g),n>1.5*k.width&&(f=b.getSmartText(p,2*n,v.height),f.x=r[l]*v.width/100,t=n,x.push(f.height)),y[l]=f;x=Math.max.apply(Math,x);v.height=x;e.height=x+2*h.v;c.node.logicArea=v;return c.bound=e};z.prototype.draw=function(){var e=this.conf,b=e.bound&&e.bound.style||{stroke:"none"},a,c,d,h,k,f,l,r,n;2<=arguments.length?(k=arguments[0],l=arguments[1]):
1<=arguments.length&&(l=arguments[0]);h=l.parentLayer;c=l.colorRange.getCumulativeValueRatio();d=l.componentPool;a=d.getKeys();this.getLogicalSpace(k,l);f=this._lSpace;k=f.node.logicArea;l=f.node.smartTexts;n=d.getComponent(this._id,a.KEY_GROUP);h=n("legend-values",h);n=d.getComponent(this._id,a.KEY_RECT);this.bound=b=n(h).attr(f.bound).css(b);n=d.getComponent(this._id,a.KEY_TEXT,!0);a=0;for(f=c.length;a<f;a++)if(r=l[a])c=k.y+r.height/2,d=a===f-1?k.x+r.x-r.width/2:a?k.x+r.x:k.x+r.x+r.width/2,n({},
h).attr({text:r.text,x:d,y:c,lineHeight:this._metaStyle.lineHeight,fill:e.style.fill});return{group:h,bound:b}};w.prototype=Object.create(z.prototype);w.prototype.constructor=w;w.prototype.getLogicalSpace=function(e,b,a){var c=this._lSpace,d=this.conf,h=d.padding,k=b.componentPool.getChart(),f,l,r,n,g,m,x=[],t,v,p,y;if(c&&!a)return c.isImpure=!0,c;c=b.colorRange;b=b.smartLabel;a=c.colorRange;l=c.getCumulativeValueRatio();c=this._lSpace={bound:{height:0,width:0},node:{logicArea:void 0,smartTexts:[]}};
y=c.node.smartTexts;g=q(e,{});g.height-=2*h.v;g.width-=2*h.h;g.x+=h.h;g.y+=h.v;b.useEllipsesOnOverflow(k.config.useEllipsesWhenOverflow);d=q(d.style,{});u(d);b.setStyle(this._metaStyle=d);p=b.getSmartText("W");k=a.length;m=(l[k-1]-l[0])/2*g.height/100;d=b.getSmartText(a[0].displayValue,g.width,m);d.y=l[0]*g.height/100;f=d.y+d.width;x.push(d.width);y[0]=d;d=b.getSmartText(a[k-1].displayValue,g.width,m);d.y=l[k-1]*g.height/100;m=d.y-d.height;x.push(d.width);y[k-1]=d;t=f;for(f=1;f<k-1;f++)d=void 0,v=
a[f].displayValue,r=f+1===k-1?m:l[f+1]*g.height/100,n=l[f]*g.height/100,r=Math.min(n-t,r-n),r>2*p.height&&(d=b.getSmartText(v,g.width,2*r),d.y=l[f]*g.height/100,t=r,x.push(d.width)),y[f]=d;x=Math.max.apply(Math,x);g.width=x;e.width=x+2*h.h;c.node.logicArea=g;return c.bound=e};w.prototype.draw=function(){var e,b,a=this.conf;b=a.bound&&a.bound.style||{stroke:"none"};var c,d,h,k,f,l,r,n;2<=arguments.length?(c=arguments[0],h=arguments[1]):1<=arguments.length&&(h=arguments[0]);e=h.parentLayer;k=h.colorRange.getCumulativeValueRatio();
f=h.componentPool;l=f.getKeys();this.getLogicalSpace(c,h);d=this._lSpace;c=d.node.logicArea;h=d.node.smartTexts;n=f.getComponent(this._id,l.KEY_GROUP);e=n("legend-values",e);n=f.getComponent(this._id,l.KEY_RECT);this.bound=b=n(e).attr(d.bound).css(b);n=f.getComponent(this._id,l.KEY_TEXT,!0);f=0;for(l=k.length;f<l;f++)if(k=h[f])d=c.x+k.width/2,r=f===l-1?c.y+k.y-k.height/2:f?c.y+k.y:c.y+k.y+k.height/2,n({},e).attr({text:k.text,x:d,y:r,lineHeight:this._metaStyle.lineHeight,fill:a.style.fill});return{group:e,
bound:b}};J.prototype.constructor=J;J.prototype.addCompositions=function(e,b){this.compositionsByCategory[b]=e};J.prototype.getLogicalSpace=function(e,b,a){b=this._lSpace;var c=this.conf,d=c.padding,h,k;k=c.legendAxisHeight;var f=this.compositionsByCategory,l;l=0;if(b&&!a)return b.isImpure=!0,b;b=this._lSpace={bound:{height:0,width:0},node:{logicArea:void 0}};a=q(e,{});a.height-=2*d.v;a.width-=2*d.h;a.x+=d.h;a.y+=d.v;c=k/2+c.line.offset;h=k/2;if(f=f.RANGE)l=f.sliders[!1],l=l.conf.outerCircle.rFactor*
k,h+=l=Math.max(l/2-k/2,0);a.y+=l;a.height=k=h+c+l;e.height=k+2*d.v;b.node.logicArea=a;return b.bound=e};J.prototype.getDrawableAxisArea=function(e){var b=this.conf;return{x:e.x,y:e.y,width:e.width,height:b.legendAxisHeight,r:b.legendAxisHeight/2}};J.prototype.preDrawingRangeParam=function(e){return{y:e.y+e.height/2,calculationBase:e.height,rangeStart:e.x,rangeEnd:e.x+e.width,prop:"y"}};J.prototype.getScaleMarkerPathStr=function(e,b){var a=q(e,{}),c=this.conf.line,d,h,k,f,l="";a.x+=a.r;a.width-=2*
a.r;f=a.y+a.height;d=0;for(h=b.length;d<h;d++)k=b[d],k=a.x+k*a.width/100,l+="M"+k+","+(f-c.grooveLength)+"L"+k+","+(f+c.offset);a=""+("M"+a.x+","+(f+c.offset)+"L"+(a.x+a.width)+","+(f+c.offset));return l+a};J.prototype.getColorGradient=function(e){return{axis:e.getBoxFill(),shadow:H({FCcolor:{alpha:"25,0,0",angle:90,color:"000000,FFFFFF,FFFFFF",ratio:"0,30,40"}})}};J.prototype.draw=function(){var e,b=this.conf,a=b.line,c=(b.bound||{}).style||{},d,h,k=this.compositionsByCategory,f,l,r,n,g,m;2<=arguments.length?
(d=arguments[0],g=arguments[1]):1<=arguments.length&&(g=arguments[0]);e=g.parentLayer;f=g.colorRange;l=f.getCumulativeValueRatio();m=g.componentPool;r=m.getKeys();this.getLogicalSpace(d,g);n=this._lSpace;d=m.getComponent(this._id,r.KEY_GROUP);e=d("legend-axis",e);d=m.getComponent(this._id,r.KEY_RECT,!0);this.bound=d(e).attr(n.bound).css(c);c=this.getDrawableAxisArea(n.node.logicArea);f=this.getColorGradient(f);b.style.fill=f.axis;b.shadow.style.fill=f.shadow;this.node=d(e).attr(c).css(b.style);this.shadow=
d(e).attr(c).css(b.shadow.style);b=this.getScaleMarkerPathStr(c,l);d=m.getComponent(this._id,r.KEY_PATH);d("M0,0",e).attr({path:b}).css(a.style);for(h in k)switch(a=k[h],h){case "RANGE":r=this.preDrawingRangeParam(c),g[r.prop]=r[r.prop],g.key=r.prop,g.rCalcBase=r.calculationBase,g.parentLayer=e,a.draw(r.rangeStart,r.rangeEnd,g)}};P.prototype=Object.create(J.prototype);P.prototype.constructor=P;P.prototype.getLogicalSpace=function(e,b,a){b=this._lSpace;var c=this.conf,d=c.padding,h,k;k=c.legendAxisHeight;
var f=this.compositionsByCategory,l;l=0;if(b&&!a)return b.isImpure=!0,b;b=this._lSpace={bound:{height:0,width:0},node:{logicArea:void 0}};a=q(e,{});a.height-=2*d.v;a.width-=2*d.h;a.x+=d.h;a.y+=d.v;c=k/2+c.line.offset;h=k/2;if(f=f.RANGE)l=f.sliders[!1],l=l.conf.outerCircle.rFactor*k,h+=l=Math.max(l/2-k/2,0);a.x+=l;a.width=k=h+c+l;e.width=k+2*d.v;b.node.logicArea=a;return b.bound=e};P.prototype.getDrawableAxisArea=function(e){var b=this.conf;return{x:e.x,y:e.y,width:b.legendAxisHeight,height:e.height,
r:b.legendAxisHeight/2}};P.prototype.getScaleMarkerPathStr=function(e,b){var a=q(e,{}),c=this.conf.line,d,h,k,f,l="";a.y+=a.r;a.height-=2*a.r;f=a.x+a.width;d=0;for(k=b.length;d<k;d++)h=b[d],h=a.y+h*a.height/100,l+="M"+(f-c.grooveLength)+","+h+"L"+(f+c.offset)+","+h;a=""+("M"+(f+c.offset)+","+a.y+"L"+(f+c.offset)+","+(a.y+a.height));return l+a};P.prototype.getColorGradient=function(e){return{axis:e.getBoxFill(!0),shadow:H({FCcolor:{alpha:"25,0,0",angle:360,color:"000000,FFFFFF,FFFFFF",ratio:"0,30,40"}})}};
P.prototype.preDrawingRangeParam=function(e){return{x:e.x+e.width/2,calculationBase:e.width,rangeStart:e.y,rangeEnd:e.y+e.height,prop:"x"}};p.prototype.constructor=p;p.prototype.initRange=function(e,b){this.extremes[+e.sliderIndex]=b};p.prototype.updateRange=function(e,b){var a=e.sliderIndex;this.sliders[!a].updateSwingRange(a,b)};p.prototype.reset=function(){var e={};e.conf=this.conf;e.sliderGroup=this;this.sliders[!1]=new C(!1,e,this._id+"_0");this.sliders[!0]=new C(!0,e,this._id+"_1");this.draw.apply(this,
this._drawParams)};p.prototype.clearListeners=function(){this.callbacks.length=0};p.prototype.draw=function(e,b,a){var c=this.sliders,d=c[!1],c=c[!0],h=a.colorRange,k=h.colorRange,f=this._fcChart=a.componentPool.getChart();this.getValueFormPixel=function(a,b,c,d){var h=(b-a)/(d-c);this.getValueFormPixel=function(b){return a+h*b}};this.updateWhenInMove=function(a,b){this.updateWhenInMove=function(c,d){var h=this.extremes,h=this.getValueFormPixel(c.sliderIndex?h[1]-h[0]+d:d);return h=b?parseFloat(h).toFixed(2)+
"%":a.legendValue(h)}};this._drawParams=[e,b,a];this.updateWhenInMove(f.components.numberFormatter,h.mapByPercent);e=d.draw(e,k[0].displayValue,a[a.key],a);e=c.draw(b,k[k.length-1].displayValue,a[a.key],a);d.swing=this.extremes.slice(0);c.swing=this.extremes.slice(0);this.getValueFormPixel(k[0].value,k[k.length-1].value,this.extremes[0],this.extremes[1]);return e};p.prototype.registerListener=function(e,b,a){this.callbacks.push({fn:e,context:b,params:a||[]})};p.prototype.updateWhenInRest=function(e,
b){var a=this.sliders,c=this.extremes,d=e.sliderIndex,h,k=this.callbacks,f,l;d?(h=a[!d].currPos,a=c[1]-c[0]+b):(h=b,a=c[1]-c[0]+a[!d].currPos);c=0;for(d=k.length;c<d;c++)f=k[c],l=f.params.slice(0),l.unshift(this.getValueFormPixel(a)),l.unshift(this.getValueFormPixel(h)),f.fn.apply(f.context,l)};p.prototype.dragStarted=function(e){var b=this.sliders,a=this.extremes,c=e.conf,d=this._fcChart;L.raiseEvent("legendpointerdragstart",{pointerIndex:+e.sliderIndex,pointers:[{value:this.getValueFormPixel(b[!1].currPos)},
{value:this.getValueFormPixel(a[1]-a[0]+b[!0].currPos)}],legendPointerHeight:c.outerRadius,legendPointerWidth:c.innerRadius,outerRadius:c.outerRadius,innerRadius:c.innerRadius},d.chartInstance,[d.id])};p.prototype.dragCompleted=function(e,b,a){var c=this.sliders,d=this.extremes,h=e.conf,k=this.getValueFormPixel(c[!1].currPos),c=this.getValueFormPixel(d[1]-d[0]+c[!0].currPos),f=this._fcChart,l;e.sliderIndex?(l=k,a=this.getValueFormPixel(d[1]-d[0]+a)):(l=this.getValueFormPixel(a),a=c);b&&L.raiseEvent("legendrangeupdated",
{previousMinValue:k,previousMaxValue:c,minValue:l,maxValue:a},f.chartInstance,[f.id]);L.raiseEvent("legendpointerdragstop",{pointerIndex:+e.sliderIndex,pointers:[{value:k},{value:c}],legendPointerHeight:h.outerRadius,legendPointerWidth:h.innerRadius,outerRadius:h.outerRadius,innerRadius:h.innerRadius},f.chartInstance,[f.id])};C.prototype.constructor=C;C.prototype.updateSwingRange=function(e,b){this.swing[+e]=b};C.prototype.draw=function(e,b,a,c){var d=c.parentLayer,h=this.conf,k=h.outerCircle,f=h.innerCircle,
l=Math.ceil(k.rFactor*c.rCalcBase/2),r=Math.ceil(f.rFactor*c.rCalcBase/2),n=l-r,g=this.rangeGroup,m=this.sliderIndex,x,t,v=c.componentPool,q=v.getKeys();h.outerRadius=l;h.innerRadius=r;this._scaleVal=b;f.style["stroke-width"]=n;n=Math.ceil(k.style["stroke-width"]/2);r+=n;t=v.getComponent(this._id,q.KEY_GROUP);d=this.node=t("fc-gl-slider",d).attr({cursor:"pointer",transform:"t0,0"});"x"===c.key?e=x=e+(m?-r:+r):(x=a,e=a=e+(m?-r:+r));g.initRange(this,e);t=v.getComponent(this._id,q.KEY_CIRCLE,!0);t(d).attr({cx:a,
cy:x,r:l}).css(k.style);t(d).attr({cx:a,cy:x,r:r}).css(f.style);b=this.tracker=t(d).attr({cx:a,cy:x,r:l+5,ishot:!0,fill:B,stroke:0,cursor:"pointer"}).trackTooltip(h.showTooltip?!0:!1).tooltip(b,null,null,!0);this._dragAPI=c=this.getDragAPI("x"===c.key);b.undrag();b.drag(c.dragging,c.dragStart,c.dragEnd);return{translateAscending:l+n}};C.prototype.getDragAPI=function(e){var b=this,a=b.node,c=b.sliderIndex,d=b.rangeGroup,h,k,f,l=b.conf.innerRadius,r;return{dragging:function(n,g,m,x,t){var v;t.stopPropagation();
t.preventDefault();v=e?g:n;c?(n=h[0]-h[1]+l,g=0):(n=0,g=h[1]-h[0]-l);if(!(b.currPos+v<n||b.currPos+v>g))return a.attr({transform:e?"t0,"+(b.currPos+v):"t"+(b.currPos+v)+",0"}),k=v,f&&clearTimeout(f),f=setTimeout(function(){d.updateWhenInRest(b,b.currPos+v)},100),b.tracker.tooltip(d.updateWhenInMove(b,b.currPos+v),null,null,!0),r=!0},dragStart:function(c,f,k){k.stopPropagation();k.preventDefault();a.attr({transform:e?"t0,"+b.currPos:"t"+b.currPos+",0"});h=h||b.swing;r=!1;d.dragStarted(b)},dragEnd:function(){var a;
d.dragCompleted(b,r,b.currPos+k);r&&(f&&clearTimeout(f),f=setTimeout(function(){d.updateWhenInRest(b,b.currPos)},100),b.currPos+=k,a=h[+c]+b.currPos,d.updateRange(b,a))}}};O.prototype.constructor=O;O.prototype.getValueRatio=function(){var e=this.colorRange,b,a,c=e.length,d=this.valueRatio,h=e[0].value,k=e[c-1].value-h,f=0;if(d)return d;d=this.valueRatio=[];for(a=0;a<c;a++)b=e[a],b=(b.value-h)/k,d.push(100*(b-f)),f=b;return d};O.prototype.getCumulativeValueRatio=function(){var e=this.colorRange,b,
a,c=e.length,d=e[0].value,h=e[c-1].value,k=[];for(a=0;a<c;a++)b=e[a],k.push((b.value-d)/(h-d)*100);return k};O.prototype.getBoxFill=function(e){var b=this.colorRange,a,c=b.length,d=[],h;h=e?90:0;for(a=0;a<c;a++)e=b[a],d.push(e.code);b={FCcolor:{alpha:"100,100,100",angle:h,color:d.join(","),ratio:this.getValueRatio().join(",")}};return H(b)};O.prototype.getColorByValue=function(e){var b=this.values,a=this.colorRange,c,d,h,k;if(void 0!==e&&null!==e){d=0;for(c=b.length;d<c;d++)if(e===b[d]){k=a[d].code;
break}else if(!d&&e<b[d]){h=!0;break}else if(d===c-1&&e>b[d]){h=!0;break}else if(e>b[d]&&e<b[d+1]){b=a[d];c=a[d+1];a=b.value;d=I(b.code);b=c.value;c=I(c.code);k=k=void 0;k=b-a;k=[Math.round(d[0]+(c[0]-d[0])/k*(e-a)),Math.round(d[1]+(c[1]-d[1])/k*(e-a)),Math.round(d[2]+(c[2]-d[2])/k*(e-a))];k=Y(k);break}if(!h)return k}};M.prototype=Object.create(aa.prototype);M.prototype.constructor=M;T.register("component",["gradientLegend","gradientLegend",{pIndex:1,enabled:!1,init:function(e){function b(b){a.data=
e.chart.jsonData.colorrange;(k=a.nData=K.legacyDataParser(a.data,b))?(a.drawOptions={smartLabel:c.linkedItems.smartLabel,colorRange:a.colorRange=h=new O(k,b,f),maxOtherSide:b.maxOtherSide},a._dontPlot=!1,h&&h._preparationGoneWrong&&(a._dontPlot=!0),a._recalculateLogicalSpace=!0,a._configure()):a._dontPlot=!0}var a=this,c=e.chart,d,h,k,f;K.init(e);f=a._chart=e.chart;a._cpool=ca(f);if(!(d=e.dataExtremes))return b;b(d)},_configure:function(){var e=this._chart,b=e.jsonData.chart,a=this.conf={},c=b.outcnvbasefont,
d=b.outcnvbasefontsize,h=b.outcnvbasefontcolor,e=e.config.dataLabelStyle,k,f,l,r,n,g,m;a.caption=E(b.legendcaption);a.legendPosition=E(b.legendposition,"bottom").toLowerCase();a.showLegend=F(b.showlegend,1);a.interactiveLegend=F(b.interactivelegend,1);a.showLegendLabels=F(b.showlegendlabels,1);k=b.legenditemfontcolor||h;f=b.legenditemfont||c;l=b.legenditemfontsize||d;r=F(b.legenditemfontbold,0);h=b.legendcaptionfontcolor||h;c=b.legendcaptionfont||c;d=b.legendcaptionfontsize||d;n=F(b.legendcaptionfontbold,
1);m=(g=b.legendaxisbordercolor?ga(fa(b.legendaxisbordercolor)):void 0)?F(b.legendaxisborderalpha,100)/100:void 0;a.axisTextItemConf={style:{fill:k?V(E(k)):e.color,fontFamily:f?E(f):e.fontFamily,fontSize:l?F(l):e.fontSize.match(/\d+/)[0],fontWeight:r?"bold":e.fontWeight}};a.legendCaptionConf={style:{fill:h?V(E(h)):e.color,fontFamily:c?E(c):e.fontFamily,fontSize:d?F(d):e.fontSize.match(/\d+/)[0],fontWeight:n?"bold":e.fontWeight,fontStyle:"normal"}};a.legendAxisConf={legendAxisHeight:11,style:{stroke:g,
"stroke-opacity":m},line:{style:{stroke:V(E(b.legendscalelinecolor,"FFF8E9"),F(b.legendscalelinealpha,100)),"stroke-width":F(b.legendscalelinethickness)}}};a.sliderGroupConf={showTooltip:F(b.showtooltip,1),outerCircle:{rFactor:F(b.sliderdiameterfactor),style:{stroke:V(E(b.legendpointerbordercolor,"757575"),F(b.legendpointerborderalpha,100))}},innerCircle:{rFactor:F(b.sliderholediameterfactor),style:{stroke:V(E(b.legendpointercolor,"FFFFFF"),F(b.legendpointeralpha,100))}}};a.legendCarpetConf={spreadFactor:F(b.legendspreadfactor),
allowDrag:!!F(b.legendallowdrag,0),captionAlignment:E(b.legendcaptionalignment,"center"),style:{fill:V(E(b.legendbgcolor,"e4d9c1"),F(b.legendbgalpha,100)),stroke:V(E(b.legendbordercolor,"c4b89d"),F(b.legendborderalpha,100)),"stroke-width":F(b.legendborderthickness,1)}}},postConfigureInit:function(){var e=this.conf,b,a,c,d,h,k,f;this.elem={};e.caption&&(a=q(K.getDefaultConf("legendCaptionConf"),e.legendCaptionConf),b=new Q(e.caption,a));e.interactiveLegend&&(a=q(K.getDefaultConf("sliderGroupConf"),
e.sliderGroupConf),this.elem.sGroup=d=new p(a),this.listeners&&0<this.listeners.length&&d.registerListener.apply(d,this.listeners));a=q(K.getDefaultConf("legendCarpetConf"),e.legendCarpetConf);"bottom"===e.legendPosition?(this.drawOptions.refSideKey="canvasWidth",this.drawOptions.refOffsetKey="canvasLeft",a=new U(a),h=q(K.getDefaultConf("axisTextItemConf"),e.axisTextItemConf),k=new y(this.drawOptions.colorRange,K.getDefaultConf("legendBodyConf"),h),c=new J(q(K.getDefaultConf("legendAxisConf"),e.legendAxisConf)),
e.showLegendLabels&&(f=new m(h)),e=new z(h)):(this.drawOptions.refSideKey="canvasHeight",this.drawOptions.refOffsetKey="canvasTop",h=q(K.getDefaultConf("axisTextItemConf"),e.axisTextItemConf),a=new g(a),k=new X(this.drawOptions.colorRange,K.getDefaultConf("legendBodyConf"),h),c=new P(q(K.getDefaultConf("legendAxisConf"),e.legendAxisConf)),e.showLegendLabels&&(f=new W(h)),e=new w(h));d&&c.addCompositions(d,"RANGE");f&&k.addCompositions(f,"LEGEND_LABEL");k.addCompositions(c,"LEGEND_AXIS");k.addCompositions(e,
"AXIS_VALUE");b&&a.addCompositions(b,"CAPTION");a.addCompositions(k,"LEGEND_BODY");this.elem.gl=new M(a,this._cpool)},notifyWhenUpdate:function(e,b,a){var c;(c=this.elem&&this.elem.sGroup)?c.registerListener(e,b,a):this.listeners=[e,b,a]},dispose:function(){this.elem&&this.elem.gl&&this.elem.gl.dispose();this.elem={}},getLogicalSpace:function(e){var b=this.conf,a={height:0,width:0},c=this.drawOptions,d=this._chart;if(!this._recalculateLogicalSpace)return b=c.refSideKey,c=c.refOffsetKey,this.drawOptions.refSide=
d.config[b],this.drawOptions.refOffset=d.config[c],(this._logicalArea=this.elem.gl.getLogicalSpace(this.drawOptions,!0))||a;if(this._dontPlot)return a;this._recalculateLogicalSpace=!1;this.postConfigureInit();if(!b.showLegend)return a;b=c.refSideKey;c=c.refOffsetKey;this.drawOptions.refSide=d.config[b];this.drawOptions.refOffset=d.config[c];this.drawOptions.maxOtherSide=e||this.drawOptions.maxOtherSide;return this.elem.gl&&(this._logicalArea=this.elem.gl.getLogicalSpace(this.drawOptions,!0))},resetLegend:function(){var e;
(e=this.elem&&this.elem.sGroup)&&e.reset()},clearListeners:function(){var e;(e=this.elem&&this.elem.sGroup)&&e.clearListeners()},draw:function(e,b,a){var c=this.conf;this._dontPlot||(this._cpool.init(a.paper),c.showLegend?(this.drawOptions.paper=a.paper,this.drawOptions.parentGroup=a.parentGroup,this.drawOptions.x=e,this.drawOptions.y=b,this.drawOptions.maxOtherSide=this.drawOptions.maxOtherSide||a.maxOtherSide,e=this.elem.gl.draw(this.drawOptions),e=e.getBBox(),c.xPos=e.x,c.yPos=e.y,c.height=e.height,
c.width=e.width,this.enabled=!0):this.enabled=!1)}}])}]);T.register("module",["private","modules.renderer.js-maps",function(){var q=this,R=q.window,u=q.hcLib,S=u.chartAPI,aa=u.addEvent,U=u.removeEvent,g=u.pluck,Q=u.imprint,y=u.extend2,X=u.parseTooltext,m=u.pluckNumber,W=u.graphics.getLightColor,z=u.dropHash,w=u.HASHSTRING,J=u.parseUnsafeString,P=u.getDashStyle,p=u.schedular,C=y(u.defaultPaletteOptions,{foregroundcolor:"333333",foregroundalpha:"100",foregrounddarkcolor:"111111",foregrounddarkalpha:"100",
foregroundlightcolor:"666666",foregroundlightalpha:"100",backgroundlightcolor:"FFFFFF",backgroundlightalpha:"100",backgroundlightangle:90,backgroundlightratio:"",backgroundcolor:"FFFFCC",backgroundalpha:"100",backgrounddarkcolor:"ffcc66",backgrounddarkalpha:"100",backgrounddarkangle:270,backgrounddarkratio:"",shadow:1}),O=u.setLineHeight,M=u.graphics.convertColor,L=R.navigator.userAgent,N=/msie/i.test(L)&&!R.opera,F=u.hasSVG,E=R.Math,H=E.min,G=E.max,fa=/stroke/ig,ga=/AppleWebKit/.test(L),V=E.ceil,
Y=Math.PI/180,I=u.hasTouch,R=!u.CREDIT_REGEX.test(R.location.hostname),A=u.toRaphaelColor,Z="rgba(192,192,192,"+(N?.002:1E-6)+")",B=function(b,a){var c;b||(b={});for(c in a)b[c]=a[c];return b},K=function(b,a){var c=a?B(b.FCcolor,a):{FCcolor:b};c.toString=A;return c},ba=function(b,a){var c,d;this.index=a;for(d in b)c=C[b[d]],this[d]=c instanceof Array?c[a]:c},da={right:function(b,a){return a},left:function(b,a){return b-a},center:function(b,a){return 2*H(a,b-a)}},ca={top:function(b,a){return a},middle:function(b,
a){return 2*H(a,b-a)},bottom:function(b,a){return b-a}},ea=function(b,a){var c=b&&b.length||!1,d=a||"id",h={},k;if(!b)return b;for(;c--;)k=b[c],void 0!==k[d]&&(h[k[d].toLowerCase()]=k);return h},e=u.KdTree;B(u.eventList,{entityrollover:"FC_Event",entityrollout:"FC_Event"});S("geo",{name:"geo",friendlyName:"Map",revision:1,creditLabel:R,hasCanvas:!0,standaloneInit:!1,defaultDatasetType:"maps",baseWidth:400,baseHeight:300,baseScaleFactor:1,defaultSeriesType:"geo",fireGroupEvent:!0,legendposition:"right",
hasGradientLegend:!0,isMap:!0,entities:{},init:function(b,a,c,d){var h,k;k=a.chart=a.chart||a.graph||a.map||{};this.jsonData=a;h=this.components=this.components||(this.components={});h.mapAnnotations=h.mapAnnotations||(h.mapAnnotations=new u.Annotations);this.components.colorPalette=new ba(this.colorPaletteMap,(0<k.palette&&6>k.palette?k.palette:m(this.paletteIndex,1))-1);k=T.register("component",["caption","MapCaption"]);h.caption||(h.caption=new k);S.mscartesian.init.call(this,b,a,c,d)},configure:function(){var b;
b=this.jsonData;var a=b.chart||b.map,c=b.markers,d=new ba(this.colorPaletteMap,(0<a.palette&&6>a.palette?a.palette:m(this.paletteIndex,1))-1),h,k,f,l,e=g(a.entitybordercolor,a.bordercolor,d.plotbordercolor),n=g(a.entityfillcolor,a.fillcolor,d.plotfillcolor),D=g(a.entityfillalpha,a.fillalpha,d.plotfillalpha),ia=g(a.entityfillratio,a.fillratio,d.plotfillratio),x=g(a.entityfillangle,a.fillangle,d.plotfillangle),t=g(a.nullentityfillcolor,a.nullentitycolor,n),v=m(a.usevaluesformarkers,b.markers&&b.markers.items&&
b.markers.items.length,!(b.markers&&b.markers.application&&b.markers.application.length&&b.markers.definition&&b.markers.definition.length));this.base.base.configure.call(this);b=this.config;b.origMarginTop=m(a.charttopmargin,a.maptopmargin,11);b.origMarginLeft=m(a.chartleftmargin,a.mapleftmargin,11);b.origMarginBottom=m(a.chartbottommargin,a.mapbottommargin,11);b.origMarginRight=m(a.chartrightmargin,a.maprightmargin,11);l=b.style;h=l.inCancolor;k=l.inCanfontFamily;f=l.inCanfontSize;b.entityOpts=
{baseScaleFactor:this.baseScaleFactor,dataLabels:{style:{fontFamily:k,fontSize:f,lineHeight:l.inCanLineHeight,color:l.inCancolor}},fillColor:n,fillAlpha:D,fillRatio:ia,fillAngle:x,borderColor:e,borderAlpha:g(a.entityborderalpha,a.borderalpha,this.borderAlpha,"100"),borderThickness:m(a.showentityborder,a.showborder,1)?m(a.entityborderthickness,a.borderthickness,1):0,scaleBorder:m(a.scaleentityborder,a.scaleborder,0),hoverFillColor:g(a.entityfillhovercolor,a.hoverfillcolor,a.hovercolor,d.plothoverfillcolor),
hoverFillAlpha:g(a.entityfillhoveralpha,a.hoverfillalpha,a.hoveralpha,d.plothoverfillalpha),hoverFillRatio:g(a.entityfillhoverratio,a.hoverfillratio,a.hoverratio,d.plothoverfillratio),hoverFillAngle:g(a.entityfillhoverangle,a.hoverfillangle,a.hoverangle,d.plothoverfillangle),hoverBorderThickness:g(a.entityborderhoverthickness,a.hoverborderthickness),hoverBorderColor:g(a.entityborderhovercolor,d.plotbordercolor),hoverBorderAlpha:g(a.entityborderhoveralpha,d.plotborderalpha),nullEntityColor:t,nullEntityAlpha:g(a.nullentityfillalpha,
a.nullentityalpha,D),nullEntityRatio:g(a.nullentityfillratio,a.nullentityratio,ia),nullEntityAngle:g(a.nullentityfillangle,a.nullentityangle,x),connectorColor:g(a.labelconnectorcolor,a.connectorcolor,h),connectorAlpha:g(a.labelconnectoralpha,a.connectoralpha,"100"),connectorThickness:m(a.labelconnectorthickness,a.borderthickness,1),showHoverEffect:m(a.showentityhovereffect,a.usehovercolor,a.showhovereffect,1),hoverOnNull:m(a.hoveronnull,a.entityhoveronnull,1),labelPadding:m(a.labelpadding,5),showLabels:m(a.showlabels,
1),labelsOnTop:m(a.entitylabelsontop,1),includeNameInLabels:m(a.includenameinlabels,1),includeValueInLabels:m(a.includevalueinlabels,0),useSNameInTooltip:m(a.usesnameintooltip,0),useShortName:m(a.usesnameinlabels,1),labelSepChar:g(a.labelsepchar,", "),showTooltip:m(a.showentitytooltip,a.showtooltip,1),tooltipSepChar:g(a.tooltipsepchar,", "),tooltext:a.entitytooltext,hideNullEntities:m(a.hidenullentities,0),showHiddenEntityBorder:m(a.showhiddenentityborder,1),showNullEntityBorder:m(a.shownullentityborder,
1),hiddenEntityColor:g(a.hiddenentitycolor,a.hiddenentityfillcolor,a.hiddenentityalpha||a.hiddenentityfillalpha?t:"ffffff"),hiddenEntityAlpha:g(a.hiddenentityalpha,a.hiddenentityfillalpha,.001),shadow:m(a.showshadow,this.defaultPlotShadow,d.shadow)};b.markerOpts={dataLabels:{style:{fontFamily:g(a.markerfont,k),fontSize:m(a.markerfontsize,parseInt(f,10)),fontColor:g(a.markerfontcolor,h)}},showTooltip:m(a.showmarkertooltip,a.showtooltip,1),showLabels:m(a.showmarkerlabels,a.showlabels,1),showHoverEffect:m(a.showmarkerhovereffect,
1),labelPadding:g(a.markerlabelpadding,"5"),labelWrapWidth:m(a.markerlabelwrapwidth,0),labelWrapHeight:m(a.markerlabelwrapheight,0),fillColor:g(a.markerfillcolor,a.markerbgcolor,d.markerfillcolor),fillAlpha:g(a.markerfillalpha,d.markerfillalpha),fillAngle:g(a.markerfillangle,d.markerfillangle),fillRatio:g(a.markerfillratio,d.markerfillratio),fillPattern:g(a.markerfillpattern,d.markerbgpattern),hoverFillColor:a.markerfillhovercolor,hoverFillAlpha:a.markerfillhoveralpha,hoverFillRatio:a.markerfillhoverratio,
hoverFillAngle:a.markerfillhoverangle,borderThickness:g(a.markerborderthickness,1),borderColor:g(a.markerbordercolor,d.markerbordercolor),borderAlpha:m(a.markerborderalpha,d.markerborderalpha),hoverBorderThickness:a.markerborderhoverthickness,hoverBorderColor:a.markerborderhovercolor,hoverBorderAlpha:a.markerborderhoveralpha,radius:m(a.markerradius&&u.trimString(a.markerradius),7),shapeId:g(a.defaultmarkershape,"circle"),labelSepChar:g(a.labelsepchar,", "),tooltipSepChar:g(a.tooltipsepchar,", "),
autoScale:m(a.autoscalemarkers,0),tooltext:g(c&&c.tooltext,a.markertooltext),dataEnabled:v,valueToRadius:m(a.markerradiusfromvalue,1),valueMarkerAlpha:g(a.valuemarkeralpha,"75"),hideNull:m(a.hidenullmarkers,0),nullRadius:m(a.nullmarkerradius,a.markerradius,7),adjustViewPort:m(a.adjustviewportformarkers,0),startAngle:m(a.markerstartangle,90),maxRadius:m(a.maxmarkerradius,0),minRadius:m(a.minmarkerradius,0),applyAll:m(a.applyallmarkers,0),shadow:m(a.showmarkershadow,a.showshadow,0)};b.connectorOpts=
{showHoverEffect:m(a.showconnectorhovereffect,1),thickness:m(a.connectorthickness,a.markerconnthickness,"2"),color:g(a.connectorcolor,a.markerconncolor,d.markerbordercolor),alpha:g(a.connectoralpha,a.markerconnalpha,"100"),hoverThickness:m(a.connectorhoverthickness,a.connectorthickness,a.markerconnthickness,"2"),hoverColor:g(a.connectorhovercolor,a.connectorcolor,a.markerconncolor,d.markerbordercolor),hoverAlpha:g(a.connectorhoveralpha,a.connectoralpha,a.markerconnalpha,"100"),dashed:m(a.connectordashed,
a.markerconndashed,0),dashLen:m(a.connectordashlen,a.markerconndashlen,3),dashGap:m(a.connectordashgap,a.markerconndashgap,2),font:g(a.connectorfont,a.markerconnfont,k),fontColor:g(a.connectorfontcolor,a.markerconnfontcolor,h),fontSize:m(a.connectorfontsize,a.markerconnfontsize,parseInt(f,10)),showLabels:m(a.showconnectorlabels,a.showmarkerlabels,a.showlabels,1),labelBgColor:g(a.connectorlabelbgcolor,a.markerconnlabelbgcolor,d.plotfillcolor),labelBorderColor:g(a.connectorlabelbordercolor,a.markerconnlabelbordercolor,
d.markerbordercolor),shadow:m(a.showconnectorshadow,a.showmarkershadow,a.showshadow,0),showTooltip:m(a.showconnectortooltip,a.showmarkertooltip,a.showtooltip,1),tooltext:g(c&&c.connectortooltext,a.connectortooltext),hideOpen:m(a.hideopenconnectors,1)};b.adjustViewPortForMarkers=m(a.adjustviewportformarkers,v)},_createLayers:function(){var b=this.graphics||(this.graphics={}),a=this.components.paper,b=this.graphics;b.backgroundGroup=b.backgroundGroup||a.group("background");b.canvasGroup=b.canvasGroup||
a.group("canvas");b.shadowGroup=b.shadowGroup||a.group("shadow");b.datasetGroup=b.datasetGroup||a.group("dataset");b.datalabelsGroup=b.datalabelsGroup||a.group("datalabel");b.legendGroup=b.legendGroup||a.group("legend");b.captionGroup=b.captionGroup||a.group("caption");b.captionGroup.trackTooltip(!0);b.datasetGroup.trackTooltip(!0);b.buttonGroup=b.buttonGroup||a.group("buttons");this._attachMouseEvents()},_attachMouseEvents:function(){var b=this.linkedItems,b=b.eventListeners||(b.eventListeners=[]),
a=this.linkedItems.container;U(a,I?"touchstart":"mousemove",this.searchMouseMove);b.push(aa(a,"touchstart mousemove",this.searchMouseMove,this))},searchMouseMove:function(b){var a=b.data,c=a.config,d={};if(a.linkedItems.container){var d=u.getMouseCoordinate(a.linkedItems.container,b),h=d.chartX,k=d.chartY,f=a.config,l=f.canvasLeft,e=f.canvasTop,n=f.canvasLeft+f.canvasWidth,f=f.canvasHeight+f.canvasTop;d.insideCanvas=!1;d.originalEvent=b;h>l&&h<n&&k>e&&k<f&&(d.insideCanvas=!0);d&&d.insideCanvas&&(c.lastMouseEvent=
b,d={x:d.chartX,y:d.chartY},a._searchNearestNeighbour(d))}},_searchNearestNeighbour:function(b){var a=this.components.dataset[1];a&&a.components.kDTree&&((b=a.getElement(b))?this.config.lastHoveredPoint!==b&&a.highlightPoint(b):a.highlightPoint(!1))},_createDatasets:function(){var b=this.components,a=this.jsonData,c=this.defaultDatasetType,d=a.data||{},h=a.markers,a=0,k=this.components.dataset,k=b.dataset||(b.dataset=[]);c&&c.toLowerCase();if(c=T.get("component",["dataset","Entities"]))k[a]?(k[a].JSONData=
d,k[a].configure()):(b=new c,k.push(b),b.chart=this,b.index=void 0,b.init(d)),a++;c=T.get("component",["dataset","Markers"]);b=k[a];c&&h?k[a]?(b.index=void 0,b.init(h),k[a].configure()):(b=new c,k.push(b),b.chart=this,b.index=void 0,b.init(h)):(d=b&&b.type,"markers"===d&&k.splice(a,1))},_parseBackgroundCosmetics:function(){var b=this.components.background.config,a=this.components.colorPalette,c=this.jsonData.chart,d;d=b.showBorder=m(c.showcanvasborder,1);b.borderWidth=d=d?m(c.canvasborderthickness,
1):0;b.borderRadius=b.borderRadius=m(c.canvasborderradius,0);b.borderDashStyle=b.borderDashStyle=m(c.borderdashed,0)?P(m(c.borderdashlen,4),m(c.borderdashgap,2),d):"none";b.borderColor=b.borderColor=M(g(c.canvasbordercolor,a&&a.borderColor));b.borderAlpha=g(c.canvasborderalpha,a.borderAlpha)},_getBackgroundCosmetics:function(){var b=this.jsonData.chart||this.jsonData.map,a=this.components.colorPalette;return{FCcolor:{color:g(b.bgcolor,b.canvasbgcolor,a.bgcolor),alpha:g(b.bgalpha,b.canvasbgalpha,a.bgalpha),
angle:g(b.bgangle,b.canvasbgangle,a.bgangle),ratio:g(b.bgratio,b.canvasbgratio,a.bgratio)}}},_parseCanvasCosmetics:function(){var b=this.config,a=this.jsonData.chart||this.jsonData.map,c=this.components.canvas.config;b.origMarginTop=m(a.maptopmargin,11);b.origMarginLeft=m(a.mapleftmargin,11);b.origMarginBottom=m(a.mapbottommargin,11);b.origMarginRight=m(a.maprightmargin,11);b.origCanvasLeftMargin=m(a.canvasleftmargin,0);b.origCanvasRightMargin=m(a.canvasrightmargin,0);b.origCanvasTopMargin=m(a.canvastopmargin,
0);b.origCanvasBottomMargin=m(a.canvasbottommargin,0);c.canvasBorderRadius=m(a.canvasborderradius,0);c.origCanvasTopPad=m(a.canvastoppadding,0);c.origCanvasBottomPad=m(a.canvasbottompadding,0);c.origCanvasLeftPad=m(a.canvasleftpadding,0);c.origCanvasRightPad=m(a.canvasrightpadding,0)},draw:function(){this.config.entitiesDrawn=!1;this.config.hasChartMessage?(this._hide(),this.drawChartMessage()):(this._show(),this._createToolBox(),this._manageSpace(),this._updateVisuals(),this.inited=!0,this.chartInstance.jsVars.drawCount+=
1,this.chartInstance.__state.dataReady=!0,this.chartInstance.jsVars.hasNativeMessage=!1)},_drawDataset:function(){var b=this.chartInstance,a=this.components.dataset,c=this.graphics,d=a.length,h=this.config.scalingParams;c.datasetGroup.hide();c.shadowGroup.hide();this.config.entitiesReady=!1;b.addEventListener("internal.mapdrawingcomplete",function(){return function(a){a.detachHandler();F&&(c.datasetGroup&&c.datasetGroup.attr({transform:h.transformStr}),c.shadowGroup&&c.shadowGroup.attr({transform:h.transformStr}));
c.datasetGroup&&c.datasetGroup.show();c.shadowGroup&&c.shadowGroup.show()}}());for(b=0;b<d;b++)a[b].draw();this.checkComplete()},preliminaryScaling:function(){for(var b=this.jsonData,a=(b=b.markers&&b.markers.items||[],b.length)||0,c=Infinity,d=Infinity,h=-Infinity,k=-Infinity,f,l;a--;)l=b[a],f=Number(l.x),l=Number(l.y),c=H(c,f),d=H(d,l),h=G(h,f),k=G(k,l);return{x:c,y:d,x1:h,y1:k}},getScalingParameters:function(b,a,c,d){var h=b/a,k=c/(b*this.baseScaleFactor),f=d/(a*this.baseScaleFactor),l=0,e=0;k>
f?(k=f,l+=(c-d*h)/2,b=200/(a*k)):(e+=(d-c/h)/2,b=200/(b*k));return{scaleFactor:k,strokeWidth:b,translateX:l,translateY:e}},calculateMarkerBounds:function(b,a,c){var d=this.config,h=d.markerOpts,k=this.components.dataset,f=this.getDataLimits(),l=f.dataMin,f=f.dataMax,e=h.hideNull,n=h.nullRadius,h=h.valueToRadius,g,m,x,t,v=Infinity,q=Infinity,p=-Infinity,y=-Infinity,u;x=0;for(t=k.length;x<t;x++)d=k[x],m=d.type,"markers"===m&&(g=d);if(g)for(x in g.calculateMarkerRadiusLimits(),m=g.conf||{},k=m.minRadius,
m=m.maxRadius,g=g.components&&g.components.markerObjs||{},g)d=g[x],d=d.config,u=d.definition||{},null!==d.cleanValue?(h&&void 0===u.radius&&(d.radius=k+(m-k)*(d.cleanValue-l)/(f-l)),t=Number(d.radius),d=(Number(u.x)+a)*b,u=(Number(u.y)+c)*b,v=H(v,d-t),q=H(q,u-t),p=G(p,d+t),y=G(y,u+t)):e?d.__hideMarker=!0:null===d.radius&&(d.radius=n);return{x:v,y:q,x1:p,y1:y}},_spaceManager:function(){var b=this.config,a=this.components.legend.config.legendPos,c=this.jsonData.chart,d=b.origMarginLeft,h=b.origMarginTop,
k=this.baseWidth,f=this.baseHeight,l,e={},g=0,D=0,q,e=b.markerOpts,c=b.borderWidth=b.showBorder?m(c.borderthickness,1):0;this._allocateSpace({top:c,bottom:c,left:c,right:c});this._allocateSpace(this._manageActionBarSpace&&this._manageActionBarSpace(.225*b.availableHeight)||{});this._manageLegendSpace("right"===a?.3*b.canvasWidth:.3*b.canvasHeight);a=this._manageChartMenuBar("bottom"===a?.225*b.canvasHeight:.225*b.canvasWidth);c=b.canvasWidth;l=b.canvasHeight;e.dataEnabled?(b.adjustViewPortForMarkers?
(e=this.preliminaryScaling(),e.x1>k&&(k=e.x1),0>e.x&&(k+=-e.x,g=-e.x),e.y1>f&&(f=e.y1),0>e.y&&(f+=-e.y,D=-e.y),b=this.getScalingParameters(k,f,c,l),e=this.calculateMarkerBounds(b.scaleFactor*this.baseScaleFactor,g,D),b=l,q=c,0>e.x&&(d+=-e.x,c+=e.x),0>e.y&&(h+=-e.y,l+=e.y),e.x1>q&&(c-=e.x1-q),e.y1>b&&(l-=e.y1-b)):(b=this.getScalingParameters(k,f,c,l),this.calculateMarkerBounds(b.scaleFactor*this.baseScaleFactor,g,D)),b=this.getScalingParameters(k,f,c,l),d+=g*b.scaleFactor*this.baseScaleFactor,h+=D*
b.scaleFactor*this.baseScaleFactor):b=this.getScalingParameters(k,f,c,l);this.config.scalingParams=b;k=b.scaleFactor;b.translateX+=d;b.translateY=b.translateY+h+a.top||0;b.sFactor=k*this.baseScaleFactor*100/100;b.transformStr=["t",b.translateX,",",b.translateY,"s",k,",",k,",0,0"].join("");this.config.annotationConfig={id:"geo",showbelow:0,autoscale:0,grpxshift:b.translateX?b.translateX:0,grpyshift:b.translateY?b.translateY:0,xscale:100*(k?k*this.baseScaleFactor:1),yscale:100*(k?k*this.baseScaleFactor:
1),options:{useTracker:!0}};this.components.mapAnnotations.reset(null,this.config.annotationConfig,this);this.components.mapAnnotations._renderer&&(this.components.mapAnnotations._renderer=null)},getDataLimits:function(){var b=this.components.dataset,a=b.length,c,d=Infinity,h=-Infinity,k;for(k=0;k<a;k++)c=b[k],c=c.getDataLimits(),d=H(d,c.min),h=G(h,c.max);return{dataMin:d,dataMax:h}},getEntityPaths:function(b){var a={},c=this.entities,d;if(b){for(d in c)a[d]=c[d];return a}return c},checkComplete:function(){var b=
this,a=b.getJobList(),c=b.components.mapAnnotations,d=b.components.mapLabelAnnotations||[],h=d.length,k,f,l=b.config.entityOpts.labelsOnTop,e,g,m=function(){b.config.labelDrawCount++;if(b.config.labelDrawCount===h&&l&&(e=c.groups&&c.groups[0]&&c.groups[0].wrapper))for(f=0;f<h;f++)(g=d[f].groups[0]&&d[f].groups[0].wrapper)&&g.insertAfter(e)};b.config.labelDrawCount=0;if(b.config.entityFlag&&b.config.entitiesReady){b.config.entityFlag=!1;for(f=0;f<h;f++)k=d[f],a.labelDrawID.push(p.addJob(k.draw,k,[b,
!0],u.priorityList.label,!0,m));c.draw(b);b.config.markersDrawn=!0;q.raiseEvent("internal.mapdrawingcomplete",{renderer:b},b.chartInstance)}},colorPaletteMap:{basefontcolor:"foregroundcolor",bordercolor:"foregrounddarkcolor",borderalpha:"foregrounddarkalpha",bgcolor:"backgroundlightcolor",bgalpha:"backgroundlightalpha",bgangle:"backgroundlightangle",bgratio:"backgroundlightratio",canvasbordercolor:"foregrounddarkcolor",canvasborderalpha:"foregrounddarkalpha",canvasbgcolor:"backgroundlightcolor",canvasbgalpha:"backgroundlightalpha",
canvasbgangle:"backgroundlightangle",canvasbgratio:"backgroundlightratio",tooltipbordercolor:"foregrounddarkcolor",tooltipborderalpha:"foregrounddarkalpha",tooltipbgcolor:"backgroundlightcolor",tooltipbgalpha:"backgroundlightalpha",tooltipfontcolor:"foregroundcolor",legendbordercolor:"foregrounddarkcolor",legendborderalpha:"foregrounddarkalpha",markerbordercolor:"foregroundlightcolor",markerborderalpha:"foregroundlightalpha",markerfillcolor:"backgrounddarkcolor",markerfillalpha:"backgrounddarkalpha",
markerfillangle:"backgrounddarkangle",markerfillratio:"backgrounddarkratio",plotfillcolor:"backgroundcolor",plotfillalpha:"backgroundalpha",plotfillangle:"backgroundangle",plotfillratio:"backgroundratio",plothoverfillcolor:"backgrounddarkcolor",plothoverfillalpha:"backgrounddarkalpha",plothoverfillangle:"backgrounddarkangle",plothoverfillratio:"backgrounddarkratio",plotbordercolor:"foregroundcolor",plotborderalpha:"foregroundalpha",shadow:"shadow"},eiMethods:{getMapName:function(){var b=this.jsVars.instanceAPI;
return"string"===typeof b.name&&b.name.toLowerCase()},getEntityList:function(){var b=this.jsVars.instanceAPI.components.dataset||[],a,c,d,h=b.length,k=[],f;for(a=0;a<h;a++)if(d=b[a]||[],f=d.type,"entity"===f){c=d;break}b=c.components.data;for(a in b)b.hasOwnProperty(a)&&(c=b[a]||{},c=c.config||{},k.push({id:c.id,originalId:c.originalId||c.id,label:c.label,shortlabel:c.shortLabel,value:c.value,formattedValue:c.formattedValue,toolText:c.toolText}));return k},getMapAttribute:function(){q.raiseWarning(this,
"12061210581","run","JavaScriptRenderer~getMapAttribute()",'Use of deprecated "getMapAttribute()". Replace with "getChartAttribute()".');return this.getChartAttribute.apply(this,arguments)},exportMap:function(){q.raiseWarning(this,"12061210581","run","JavaScriptRenderer~exportMap()",'Use of deprecated "exportMap()". Replace with "exportChart()".');return this.exportChart&&this.exportChart.apply(this,arguments)},addMarker:function(b){var a=this.jsVars.instanceAPI.components.dataset||[],c=a.length,
d,h,k,f;for(d=0;d<c;d++)if(h=a[d]||[],f=h.type,"markers"===f){k=h;break}k&&!k.addMarkerItem(b)&&q.raiseWarning(this,"1309264086","run","MapsRenderer~addMarker()","Failed to add marker. Check the options and try again.")},updateMarker:function(b,a){var c=this.jsVars.instanceAPI.components.dataset||[],d=c.length,h,k,f,l;for(h=0;h<d;h++)if(k=c[h]||[],l=k.type,"markers"===l){f=k;break}f&&b&&(b=(b+"").toLowerCase(),f.updateMarkerItem(b,a))},removeMarker:function(b){var a=this.jsVars.instanceAPI.components.dataset||
[],c=a.length,d,h,k,f;for(d=0;d<c;d++)if(h=a[d]||[],f=h.type,"markers"===f){k=h;break}b&&(b=(b+"").toLowerCase(),k._removeMarkerItem(b))}},_createAxes:function(){}},S.mscartesian);T.register("component",["caption","MapCaption",{configure:function(){var b=this.chart,a=b.jsonData.chart,c=b.components,d=c.caption.config,h=b.config.style,b=h.outCanfontFamily,k=h.outCancolor,h=h.fontSize,f=["top","center"],c=c.subCaption.config;d.style={fontFamily:g(a.captionfont,b),color:M(g(a.captionfontcolor,k).replace(/^#? ([a-f0-9]+)/ig,
"#$1")),fontSize:m(a.captionfontsize,h+3)+"px",fontWeight:0===m(a.captionfontbold)?"normal":"bold"};d.align=c.align=g(a.captionposition,"center");d.align&&(f=d.align.split("-"),f[0]&&(f[0]=f[0].toLowerCase()),f[1]&&(f[1]=f[1].toLowerCase()));d.isOnTop="bottom"===f[0]?c.isOnTop=0:c.isOnTop=1;switch(f[1]){case "right":d.align="end";break;case "left":d.align="start";break;default:d.align="middle"}d.alignWithCanvas=c.alignWithCanvas=m(a.aligncaptionwithcanvas,1);d.horizontalPadding=c.horizontalPadding=
m(a.captionhorizontalpadding,d.alignWithCanvas?0:15);d.drawCaption=!0;O(d.style);c.style={fontFamily:g(a.subcaptionfont,a.captionfont,b),color:M(g(a.subcaptionfontcolor,a.captionfontcolor,k).replace(/^#? ([a-f0-9]+)/ig,"#$1")),fontSize:m(a.subcaptionfontsize,m(G(m(a.captionfontsize)-3,-1),h)+m(this.subTitleFontSizeExtender,1))+"px",fontWeight:0===m(a.subcaptionfontbold,this.subTitleFontWeight,a.captionfontbold)?"normal":"bold"};O(c.style)}},"Caption"]);T.register("component",["dataset","Entities",
{customConfigFn:"_createDatasets",type:"entity",pIndex:2,configure:function(){var b=this.chart,a=b.jsonData,c=this.conf,d=b.components,h=a.map||a.chart,k,b=u.nonGradientColorRange,f=(a.colorrange||{}).gradient,l=d.postLegendInitFn,e=d.numberFormatter,g,D={},d=a.entitydef||[];k=a.data&&a.data[0]&&a.data[0].data?this.JSONData=a.data[0].data||[]:this.JSONData=a.data||[];c.useSNameAsId=m(h.usesnameasid,0);this._redefineEntities(d);d=this.components.data;c.showTooltip=m(h.showtooltip,1);c.showHoverEffect=
m(h.showhovereffect,0);k=(c=k)&&c.length||0;for(h={};k--;)D=c[k],void 0!==D.id&&(h[D.id.toLowerCase()]=D);k=h;this.calculateDataLimits();D=this.getDataLimits();f?l({min:D.min,max:D.max}):this.components.colorRange=new b({colorRange:a.colorrange,dataMin:D.min,dataMax:D.max,defaultColor:"#00ff00",numberFormatter:e});for(g in d)a=k[g],b=d[g],b.dataset=this,a?this._configureEntity(g,b,Q(this._sanitizeEntityOptions(y({},a)),b.config)):this._configureEntity(g,b,b.config);this._addLegend()},init:function(b){this.JSONData=
{data:b};this.components={};this.conf={};this.graphics={};this.configure()},updateEntityColors:function(b,a){var c=this.components.data,d=this.chart,h,k,f,l,e={"fill-opacity":0};for(l in c)h=c[l],k=h.config,f=k.cleanValue,k=k.alphaArr||[],k={"fill-opacity":k[0]/100||1},f<b||f>a?(this.setCustomAttrs(h,e,d),h.hidden=!0):(h.hidden=!1,this.setCustomAttrs(h,k,d))},_addLegend:function(){var b=this.chart.components.legend,a=(this.components.colorRange||{}).colorArr||[],c=this.components.entityColorMap=this.components.entityColorMap||
(this.components.entityColorMap=[]),d,h,k=a.length,f,l,e;b.emptyItems();h=c.length=0;for(k=a.length;h<k;h++)d=a[h],l=g(d.code,d.color),f=W(l,60).replace(z,w),e=W(l,40),l={FCcolor:{color:l+","+l+","+e+","+l+","+l,ratio:"0,70,30",angle:270,alpha:"100,100,100,100,100"}},f={fillColor:A(l),label:g(d.label,d.displayvalue),strokeColor:A(f),legendItemId:d.legendItemId},(l=c[h])||(l=c[h]={config:{}}),l.config=d,l.visible=!0,l.dataset=this,l.legendItemId=b.addItems(l,this.legendInteractivity,f)},legendInteractivity:function(b,
a){var c=this.config,d=b.config,h=b.visible,k=b.dataset,f=k.chart,l=k.components.data,e,g,m=a.config,q=a.graphics,x,t=k.components.colorRange,v=c.itemHiddenStyle.color,c=c.itemStyle.color,p=m.fillColor;g={};var u,y={},w={"fill-opacity":0},A=m.strokeColor;b.visible=!h;for(e in l)l.hasOwnProperty(e)&&(g=l[e],m=g.config,x=m.cleanValue,x=t.getColorObj(x),m=m.visibleEntityAttr,y["fill-opacity"]=m["fill-opacity"],m=h?w:y,d.code===x.code&&(g.hidden=h?!0:!1,k.setCustomAttrs(g,m,f)));g={legendItemSymbol:{fill:h?
v:p,stroke:h?v:A},legendItemText:{fill:h?v:c},legendIconLine:{stroke:h?v:p}};for(u in q)(d=q[u])&&d.attr&&d.attr(g[u])},setCustomAttrs:function(b,a,c){var d=c.get("config","animationObj");c=d.transposeAnimDuration;d=d.animType;b&&(b=b.graphics,b=b.outlines,b.animate(a,c,d))},calculateDataLimits:function(){var b=this.chart,a=this.conf,c=b.jsonData.data||[],b=b.components.numberFormatter,d,h=Infinity,k=-Infinity,f,l;l=0;for(f=c.length;l<f;l++)d=c[l].value,d=b.getCleanValue(d),h=H(h,d),k=G(k,d);a.max=
k;a.min=h},_configureEntity:function(b,a,c){var d=this.chart,h=this.conf,k=d.jsonData,f=d.components,l=f.numberFormatter,e=d.config.entityOpts,n=a.config,d=a.labelConfig,D=c.value,q=k.colorrange&&k.colorrange.gradient,x=(f=f.gradientLegend)&&f.colorRange,t=this.components.colorRange,f=n.cleanValue=l.getCleanValue(D),v=n.formattedValue=f?l.dataLabels(f):void 0,l=m(c.showtooltip,e.showTooltip),k=this._getDefaultTooltip.call(a,c,this),v={formattedValue:v,sName:c.shortLabel,lName:c.label},p=e.dataLabels.style,
l=n.toolText=l?J(g(X(g(c.tooltext,e.tooltext,k),[1,2,7,38,39],v,c))):"",k=n.borderColor=g(c.bordercolor,e.borderColor),v=n.borderAlpha=g(c.borderalpha,e.borderAlpha),u=n.borderThickness=m(c.borderthickness,e.borderThickness),y=n.useHoverColor=m(c.showhovereffect,c.usehovercolor,e.hoverOnNull?e.showHoverEffect:isNaN(D)?0:e.showHoverEffect),D=n.labelAlignment,w;a.hidden=!1;n.showLabel=m(c.showlabel,e.showLabels);n.labelPadding=m(c.labelpadding,e.labelPadding);n.fontFamily=g(c.font,p.fontFamily);n.fontSize=
m(parseInt(c.fontsize,10),parseInt(p.fontSize,10));n.fontBold=m(c.fontbold,0);n.fontColor=g(c.fontcolor,p.color);n.connectorColor=g(c.labelconnectorcolor,e.connectorColor);n.connectorAlpha=g(c.labelconnectoralpha,e.connectorAlpha);n.hoverBorderThickness=m(c.borderhoverthickness,c.hoverborderthickness,e.hoverBorderThickness);n.hoverBorderColor=g(c.borderhovercolor,c.hoverbordercolor,e.hoverBorderColor,n.borderColor);n.hoverBorderAlpha=g(c.borderhoveralpha,c.hoverborderalpha,e.hoverBorderAlpha,n.borderAlpha);
n.connectorThickness=m(c.labelconnectorthickness,e.connectorThickness);n.origConnectorThickness=n.connectorThickness;n.borderThickness=u;n.link=c.link;n.isVisible=!0;n.id=b;n.originalId=c.origId;null!==f&&(x&&q?w=x.getColorByValue(f):t&&(b=t.getColorObj(f),w=g(b.color,b.code)));void 0!==g(c.color,c.alpha,c.angle,c.ratio)?(w=g(c.color,w,e.fillColor),b=g(c.alpha,e.fillAlpha),f=g(c.angle,e.fillAngle),q=g(c.ratio,e.fillRatio),w=K({color:w,alpha:b,angle:f,ratio:q})):(w=K({color:g(w,e.fillColor),alpha:g(e.fillAlpha),
angle:g(e.fillAngle),ratio:g(e.fillRatio)}),b=K({color:g(e.nullEntityColor),alpha:g(e.nullEntityAlpha),angle:g(e.nullEntityAngle),ratio:g(e.nullEntityRatio)}),w=null===f?b:w,b=w.FCcolor.alpha);""===l&&(h.showTooltip=0);n.visibleEntityAttr={stroke:M(k,v),fill:(n.fillColor=w).toString(),"fill-opacity":b/100};h=b.split(",");n.alphaArr=h;y&&(void 0!==g(c.fillhovercolor,c.fillhoveralpha,c.fillhoverangle,c.fillhoverratio,c.hoverfillcolor,c.hoverfillalpha,c.hoverfillratio,c.hoverfillangle)?(w=g(c.fillhovercolor,
c.hoverfillcolor,e.hoverFillColor),b=g(c.fillhoveralpha,c.hoverfillalpha,e.hoverFillAlpha),f=g(c.fillhoverangle,c.hoverfillangle,e.hoverFillAngle),q=g(c.fillhoverratio,c.hoverfillratio,e.hoverFillRatio),h=K({color:w,alpha:b,angle:f,ratio:q})):(e.hoverColorObject||(e.hoverColorObject=K({color:e.hoverFillColor,alpha:e.hoverFillAlpha,angle:e.hoverFillAngle,ratio:e.hoverFillRatio})),h=e.hoverColorObject),n.hoverColor=h);!d&&(d=a.labelConfig={});e=n.fontColor;b=n.fontFamily;w=n.fontBold;l=n.toolText;f=
n.link;D?(h=D[0],D=D[1]):(h="center",D="middle");d.align=h;d.vAlign=D;d.bgColor="";d.borderColor="";d.fontColor=e;d.fontFamily=b;d.fontBold=w;d.toolText=l;d.link=f;if("object"===typeof n.options)for(f=n.entityLabels=n.entityLabels||[],k=n.labels||[],v=k.length;v--;)f[v]||(f[v]={config:{}}),d=f[v].config,(D=k[v].labelAlignment)?(h=D[0],D=D[1]):(h="center",D="middle"),d.align=h,d.vAlign=D,d.displayValue=this.getDisplayValue.call(a,k[v],n.options.isDataEnabled,!v,c),d.bgColor="",d.borderColor="",d.toolText=
l,d.align=h,d.vAlign=D,d.bgColor="",d.borderColor="",d.fontColor=e,d.fontFamily=b,d.fontBold=w,d.toolText=l;else n={shortText:n.shortLabel,text:n.label},d.displayValue=this.getDisplayValue.call(a,n,!0,!0,c)},getDisplayValue:function(b,a,c,d){var h=this.dataset.chart.config.entityOpts,k=this.config,f=k.cleanValue,e=k.formattedValue,m=h.labelSepChar;a?c&&"undefined"!==typeof d.displayvalue?b=d.displayvalue:(b=g(h.includeNameInLabels?h.useShortName?b.shortText:b.text:""),h.includeValueInLabels&&null!==
f&&(b=void 0===b?e:b+m+e)):b=k.label;return b},_sanitizeEntityOptions:function(b){delete b.outlines;delete b.label;delete b.shortlabel;delete b.labelposition;delete b.labelalignment;delete b.labelconnectors;return b},_redefineEntities:function(b){var a=this.conf,c={},d={},h=this.chart.entities,k=a.useSNameAsId,f,e,g,n,m,q,x,t=0,v,p;for(f=b.length;f--;)if(e=b[f],g=e.internalid,n=e.newid?e.newid:g,m=e.sname,q=e.lname,v=h[g],g=u.trimString(g),n=(n=u.trimString(n))&&n.toLowerCase(),v){c[n]=n={origId:g};
d[g]=!0;for(p in v)n[p]=v[p];n.shortLabel=m?m:v.shortLabel;n.label=q?q:v.label;n.showhovereffect=e.showhovereffect;n.fillhovercolor=e.fillhovercolor;n.fillhoveralpha=e.fillhoveralpha;n.fillhoverangle=e.fillhoverangle;n.fillhoverratio=e.fillhoverratio;n.borderhoverthickness=e.borderhoverthickness}v=this.components.data;v||(v=this.components.data={});for(x in c)x=x.toLowerCase(),v[x]||(v[x]={config:{}}),v[x].config=c[x],t+=1;c=v;for(x in h)if(n=h[x],x=u.trimString(x),!d[x]){k?((v=c[n.shortLabel.toLowerCase()])||
(v=c[n.shortLabel.toLowerCase()]={}),v.config={},v.origId=n.shortLabel):((v=c[x.toLowerCase()])||(v=c[x.toLowerCase()]={}),v.config={},v.config.origId=x);for(p in n)v.config[p]=n[p];t+=1}a.entityCount=t},draw:function(){var b=this.conf,a=this.chart,c=F?200:10;this.conf.ready=!1;b.BATCH_SIZE=c;b.labelBatchSize=F?200:20;this._batchRender()(0);a.config.entityFlag=!0},_batchRender:function(){var b=this,a=b.conf,c=b.chart,d=c.getJobList(),c=c.entities.firstEntity,h=b.components.data,k=a.BATCH_SIZE,f=a.entityKeys=
c?b._getKeys(c,h):Object.keys(h),e=a.entityLength=f.length,g,n,m,q,x,t=function(a){g=a;for(m=0;void 0!==f[g];){n=h[f[g]];x=b.drawEntity(n,k);m+=x;if(n.config.drawn){if(q=g===e-1?n:h[f[g-1]])q.config.drawn=!1,q.config.outlineStartIndex=void 0;g++}if(m>=k){d.entityDrawID.push(p.addJob(t,b,[g],u.priorityList.entitydraw,!0));break}}g===e&&(b._addEventListenersToEntities(0),b.initComplete())};return t},_addEventListenersToEntities:function(b){for(var a=this.components.data,c=this.chart.getJobList(),d=
this.conf,h=d.BATCH_SIZE,k=d.entityKeys,d=d.entityLength,f,e=0,g;b<d;b++)if(f=a[k[b]],g=f.config,(g=g.options)&&!1===g.isDataEnabled||this.addMouseGestures.call(f),e++,e===h){c.entityDrawID.push(p.addJob(this._addEventListenersToEntities,this,[b],u.priorityList.entitydraw,!0));break}},_getKeys:function(b,a){for(var c=[b],d=b;a[d];)d=a[d].nextId,c.push(d);return c},_getDefaultTooltip:function(b){var a=this.config.cleanValue,c=this.config.formattedValue,d=this.dataset.chart.config.entityOpts;if("object"===
typeof this.config.options){b=b.labels&&b.labels[0];if(!b)return;a=(d.useSNameInTooltip?b.shortText:b.text)+(null===a?"":d.tooltipSepChar+c)}else a=(d.useSNameInTooltip?b.shortLabel:b.label)+(null===a?"":d.tooltipSepChar+c);return a},drawEntity:function(b,a){var c=this.chart,d=c.components.paper,h=b.config,k=F||!N?"litepath":"path",f=h.outlines,e=c.graphics.datasetGroup,g=c.graphics.shadowGroup,n=h.toolText,c=c.config.entityOpts.shadow,m,q=[],x,t,v,p,u,w,A,B;this._configureEntityDrawingParams(b);
h=b.config;t=h.visibleEntityAttr;B=h.shadowOptions;x=h.fillOpacity;m=void 0===h.outlineStartIndex?f.length:h.outlineStartIndex;b.graphics||(b.graphics={});w=0;q=h.outlinePath||(h.outlinePath=[]);A=h.customStrokeWidthModifier;if("object"===typeof h.options){for(;m--;){q=f[m].outline;if(!0===h.options.isDataEnabled)v=t;else{v=y({},t);p=f[m].style;u=A;var z=void 0,C={};u=u||1;if(p&&"object"===typeof p)for(z in p)fa.test(z)||("stroke-width"===z?(C[z]=Number(p[z])/u,ga&&(C[z]=C[z]&&V(C[z])||0)):C[z]=p[z]);
p=C;v=y(v,p)}p=b.graphics.outlines;p||(p=b.graphics.outlines=[]);!p[m]&&(p[m]={});(u=p[m].outline)?u.attr({"fill-opacity":x}):u=p[m].outline=d[k](q,e);u.attr(v).tooltip(n).shadow(c?B:!1,g);w++;h.outlineStartIndex=m;if(w===a)return w}h.drawn=!0}else{if(b.graphics.outlines)b.graphics.outlines.attr(t).attr({"fill-opacity":x});else{for(;m--;)if(x=f[m],q=x.concat(q),w++,h.outlineStartIndex=m,w===a)return h.outlinePath=q,w;b.graphics.outlines=d[k](q,e).attr(t)}h.drawn=!0;h.outlineStartIndex=0;h.outlinePath=
[];b.graphics.outlines.tooltip(n).shadow(c?B:!1,g)}return w},_configureEntityDrawingParams:function(b){var a=this.chart,c=a.config,d=a.components.gradientLegend,h=b.config,k=a.config.scalingParams,f=!N||F,e=k.scaleFactor,g=k.strokeWidth,n=(f?a.baseScaleFactor:1)*g,m=1===a.config.entityOpts.scaleBorder,q=h.borderThickness,p=h.origConnectorThickness,t=h.hoverBorderThickness,v=h.visibleEntityAttr,u=v["fill-opacity"];h.shadowOptions={scalefactor:[e,e*a.baseScaleFactor],opacity:G.apply(E,h.alphaArr)/100};
d&&!0===c.gLegendEnabled&&(b.hidden=!1);h.fillOpacity=b.hidden?0:u;d&&d.enabled&&(d.resetLegend(),d.clearListeners());d&&d.notifyWhenUpdate(this.updateEntityColors,this);f?(q=h.entityBorderThickness=m?q*n:q/e,p/=e,b=m?e:k.sFactor,t&&(h.hoverBorderThickness=m?t*n:t/e)):(q=m?q*g:q,b=m?k.scaleFactor:a.baseScaleFactor);h.entityBorderThickness=q;h.connectorThickness=p;h.customStrokeWidthModifier=b;v["stroke-width"]=q;v.transform=F||!N?"":k.transformStr},drawLabels:function(b){var a=b.chart,c=b.conf,d=
c.labelBatchSize,h=a.components,c=c.entityLength,e=[],f,l=0,g=0,n=0,m=a.config.annotationConfig,q=h.mapLabelAnnotations=h.mapLabelAnnotations||(h.mapLabelAnnotations=[]);(h=q[l])||(h=q[l]=new u.Annotations);h.reset(null,m,a);h._renderer&&(h._renderer=null);for(f in this)b.drawLabel.call(this[f],e),l++,l===d?(h.addGroup({id:"entityLabels",items:e}),g++,(h=q[g])||(h=q[g]=new u.Annotations),h.reset(null,m,a),h._renderer&&(h._renderer=null),l=0,e=[]):n===c-1&&h.addGroup({id:"entityLabels",items:e}),n++;
b.drawLabelConnFn(0)},drawLabelConnFn:function(b){for(var a=this.conf,c=this.chart.getJobList(),d=this.components.data,h=a.BATCH_SIZE,a=a.entityKeys,e,f=a.length,l,g,n=0;b<f;b++){g=d[a[b]];e=g.config;if("object"===typeof e.options)for(e=(l=e.labels)&&l.length||0;e--;)l[e].labelConnectors&&(this.drawLabelConnectors.call(g,l[e].labelConnectors),n++);else e.labelConnectors&&(this.drawLabelConnectors.call(g,e.labelConnectors),n++);if(n===h){c.entityDrawID.push(p.addJob(this.drawLabelConnFn,this,[b],u.priorityList.entitydraw,
!0));break}}},_getLabelObject:function(b,a){var c=this,d=c.dataset,h=d.chart,e=c.config,f,l=h.config.scalingParams,g,n,m=c.graphics&&c.graphics.outlines,p,x=e.fontSize,t=e.labelPadding;n=e.labels||[];f=e.entityLabels||[];var v;void 0!==b?(n=n[b],p=f[b],f=p.config,p=f.style=n.style,g=n.labelPosition,n=n.labelAlignment):(f=c.labelConfig,g=e.labelPosition,n=e.labelAlignment);g?(m=g[0],g=g[1]):(g=m.getBBox(),m=g.x+g.width/2,g=g.y+g.height/2);n?(v=n[0],n=n[1],"right"===v?m-=t:"left"===v&&(m+=t),"top"===
n?g-=t:"bottom"===n&&(g+=t)):(v="center",n="middle");x=parseFloat(x)/l.sFactor;!a&&p&&(p.color&&(f.fontColor=p.color),p["font-size"]&&(x=parseFloat(p["font-size"])/l.sFactor),p["font-family"]&&(f.fontFamily=p["font-family"]),void 0!==p["font-weight"]&&(f.fontBold="bold"===p["font-weight"]));f.x=m.toString();f.y=g.toString();f.wrap=1;f.type="text";f.fontSize=x;return{x:m.toString(),y:g.toString(),wrapwidth:da[v](void 0,m+void 0)-t,wrapheight:ca[n](void 0,g+void 0)-t,wrap:1,type:"text",align:f.align,
valign:f.vAlign,text:f.displayValue,tooltext:f.toolText,link:f.link,bgcolor:f.bgColor,bordercolor:f.borderColor,fillcolor:f.fontColor,fontsize:f.fontSize,font:f.fontFamily,bold:f.fontBold,onclick:function(a){q.raiseEvent("entityclick",e.eventArgs,h.chartInstance,a)},onmouseover:function(a){var b=c.graphics.outlines,h,e;if(b instanceof Array)for(h=0,e=b.length;h<e;h++)d.entityRollOver.call(b[h].outline,a);else d.entityRollOver.call(b,a)},onmouseout:function(a){var b=c.graphics.outlines,h,e;if(b instanceof
Array)for(h=0,e=b.length;h<e;h++)d.entityRollOut.call(b[h].outline,a);else d.entityRollOut.call(b,a)},ontouchstart:function(a){var b=c.graphics.outlines,h,e;if(b instanceof Array)for(h=0,e=b.length;h<e;h++)d.entityRollOver.call(b[h].outline,a);else d.entityRollOver.call(b,a);d.entityRollOver.call(b,a)}}},drawLabel:function(b){var a=this.dataset,c=this.config,d;if(c.showLabel)if("object"===typeof c.options)for(d=(d=c.labels)&&d.length||0,c=c.options.isDataEnabled;d--;)b.push(a._getLabelObject.call(this,
d,c,!d));else b.push(a._getLabelObject.call(this,void 0,!0,!0))},drawLabelConnectors:function(b){for(var a=this.config,c=this.dataset.chart,d=c.components.paper,h=c.config.scalingParams,c=c.graphics.datasetGroup,e=b&&b.length||0,f,g,m=a.showLabel;e--;)g=b[e],f=this.graphics.connectorElem,m?(f||(this.graphics.connectorElem=f=d.path(g,c)),f.show().attr({transform:F||!N?"":h.transformStr,stroke:M(a.connectorColor,a.connectorAlpha),"shape-rendering":"crisp","stroke-width":a.connectorThickness})):f&&f.hide()},
entityClick:function(b){var a=this.node.__entity,c=a.dataset.chart,d=c.linkedItems.linkClickFN,a=a.config,h=a.link;q.raiseEvent("entityclick",a.eventArgs,c.chartInstance,b);void 0!==h&&d.call({link:h},c)},entityRollOver:function(b){var a=this.node.__entity,c=a.config,d=a.dataset.chart,h=c.hoverAttr;u.plotEventHandler.call(this,d,b,"entityRollOver");this.data("hovered")?clearTimeout(a.config.timer):c.useHoverColor&&c.isVisible&&!a.hidden&&(d.config.hoverEntity=this,this.attr(h),this.data("hovered",
!0))},entityRollOut:function(b){var a=this,c=this.node.__entity,d,h=c.config.revertAttr;u.plotEventHandler.call(a,c.dataset.chart,b,"entityRollOut");c.config.timer=setTimeout(function(){d=c.hidden;!0!==d&&(a.attr(h),a.data("hovered",!1))},100)},addMouseGestures:function(){var b=this,a=b.config,c=b.dataset,d=b.graphics,h=a.hoverBorderThickness,e=a.hoverBorderColor,f=a.hoverBorderAlpha,g=a.entityBorderThickness,r=a.borderColor,n=a.borderAlpha,q=a.link,p=a.visibleEntityAttr,x="groupId"+a.originalId,
t,v=function(d){void 0!==q&&d.css({cursor:"pointer",_cursor:"hand"});d.data("eventArgs",a.eventArgs);d.data("groupId",x);d.node.__entity=b;b._listenersBinded||d.click(c.entityClick).hover(c.entityRollOver,c.entityRollOut)};a.eventArgs={value:a.cleanValue,label:a.label,shortLabel:a.shortLabel,originalId:a.origId,id:a.id||a.origId};a.legacyEventArgs={value:a.value,lName:a.label,sName:a.shortLabel,id:a.originalId||a.id};a.hoverAttr={fill:A(a.hoverColor)};a.revertAttr={fill:A(a.fillColor),stroke:A(a.borderColor,
a.borderAlpha)};a.revertAttr["fill-opacity"]=p["fill-opacity"];h!==g&&(a.hoverAttr["stroke-width"]=m(h,g),a.revertAttr["stroke-width"]=g);if(e!==r||f!==n)a.hoverAttr.stoke=M(e,f),a.revertAttr.stroke=M(r,n);for(t in d)if(d.hasOwnProperty(t)){if(d[t]instanceof Array)for(g=d[t],h=0,f=g.length;h<f;h++)e=g[h].outline,v(e);else e=d[t],v(e);b._listenersBinded=!0}},getDataLimits:function(){var b=this.conf;return{max:b.max,min:b.min}},initComplete:function(){var b=this.chart;this.drawLabels.call(this.components.data,
this);b.config.entitiesReady=!0;b.checkComplete()}}]);T.register("component",["dataset","Markers",{type:"markers",configure:function(){var b=this.chart.config.markerOpts;this.calculateDataLimits();b.dataEnabled?this._parseMarkers():this.defineMarkersNShapes();this.configureConnectors()},init:function(b){this.JSONData=b;this.components={};this.conf={};this.graphics={};this.configure()},calculateMarkerRadiusLimits:function(){var b=this.JSONData,a=this.conf,c=this.chart,b=this.getMarkerRadiusLimits(c.config.width,
c.config.height,b.markermaxradius,b.markerminradius);a.minRadius=b.min;a.maxRadius=b.max},calculateDataLimits:function(){var b=this.chart,a=this.conf,c=(b.jsonData.markers||{}).items||[],b=b.components.numberFormatter,d=Infinity,h=-Infinity,e,f,g;g=0;for(f=c.length;g<f;g++)e=c[g],e=e.value,e=b.getCleanValue(e),null!==e&&(d=H(e,d),h=G(e,h));a.min=d;a.max=h},_parseMarkers:function(){var b=this.chart,a=b.jsonData.markers,c=a.items,d=a.shapes,a=b.config.markerOpts,h=b.components.numberFormatter,e=this.components.shapeObjs=
this.components.shapeObjs||(this.components.shapeObjs={}),f=this.components.markerObjs=this.components.markerObjs||(this.components.markerObjs={}),l,r,n,q,p,x,t;if(c&&c.length){if(d&&d.length)for(l=d.length;l;--l)if(n=d[l-1],t=n.id.toLowerCase())e[t]=n;for(l=c.length;l--;)if(n=c[l],t=n.id&&n.id.toLowerCase())d=n.value,void 0!==d&&""!==d&&(d=parseFloat(d)),r=this._initializeMarkerItem(t,n,null,b),(q=r.config.options.shapeid)&&"string"===typeof q&&(q=q.toLowerCase()),p=r.config,x=p.options,p.cleanValue=
h.getCleanValue(d),p.formattedValue=null!==p.cleanValue?h.dataLabels(d):void 0,p.fillColor=g(x.fillcolor,x.color,a.fillColor),p.fillAlpha=g(x.fillalpha,x.alpha,a.fillAlpha),p.fillRatio=g(x.fillratio,a.fillRatio),p.fillAngle=g(x.fillangle,a.fillAngle),p.borderThickness=m(x.borderthickness,a.borderThickness),p.borderColor=g(x.bordercolor,a.borderColor),p.borderAlpha=g(x.borderalpha,a.borderAlpha),p.labelPadding=x.labelpadding||a.labelPadding,r.dataset=this,n.__hideMarker&&(r._isHidden=!0),q&&(r.shapeObj=
e[q]),f[t]=r}},defineMarkersNShapes:function(){var b=this.chart,a=b.jsonData.markers,c=a.definition,d=b.components.numberFormatter,e=b.config.markerOpts,k=ea(c)||{},f=ea(a.application)||{},l=a.shapes,a=this.components.shapeObjs=this.components.shapeObjs||(this.components.shapeObjs={}),r=this.components.markerObjs=this.components.markerObjs||(this.components.markerObjs={}),n,q,p,x;if(c&&c.length){if(l&&l.length)for(c=l.length;c;--c)if(n=l[c-1],x=n.id.toLowerCase())a[x]=n;for(x in k)n=k[x],c=r[x]=this._initializeMarkerItem(x,
n,f[x],b),c.dataset=this,p=c.config.options.shapeid,l=c.config,q=n.value,l.cleanValue=d.getCleanValue(q),n=l.options,l.formattedValue=null!==l.cleanValue?d.dataLabels(q):void 0,l.fillColor=g(n.fillcolor,n.color,e.fillColor),l.fillAlpha=g(n.fillalpha,n.alpha,e.fillAlpha),l.fillRatio=g(n.fillratio,e.fillRatio),l.fillAngle=g(n.fillangle,e.fillAngle),l.borderThickness=m(n.borderthickness,e.borderThickness),l.borderColor=g(n.bordercolor,e.borderColor),l.borderAlpha=g(n.borderalpha,e.borderAlpha),l.labelPadding=
n.labelpadding||e.labelPadding,l.options.tooltext=g(n.tooltext,e.tooltext),l.link=n.link,p&&(c.shapeObj=a[p.toLowerCase()])}},getMarkerRadiusLimits:function(b,a,c,d){a=H(b,a);b=.02*a;a*=.07;d=parseFloat(d);c=parseFloat(c);return isNaN(d)||isNaN(c)?isNaN(d)?isNaN(c)?{min:b,max:a}:{min:parseInt(c/10,10),max:c}:{min:d,max:10*d}:d<c?{min:d,max:c}:{min:c,max:d}},getDataLimits:function(){var b=this.conf;return{min:b.min,max:b.max}},_initializeMarkerItem:function(b,a,c){var d={},e=d.config;e||(e=d.config=
{});e.id=b;e.definition=a;e.application=c;e.hasValue=null;e.value=null;e.options=null;e.label=null;e.markerShape=null;e.markerLabel=null;e.drawOptions={shape:null,label:null};e.drawComplete=!1;b=d.config.options=y({},e.definition);e.dataEnabled?isNaN(b.value)||""===b.value||(d.value=parseFloat(b.value),d.hasValue=!0):e.applyAll?e.options=y(b,e.application):c&&(e.options=y(b,e.application));return d},configureConnectors:function(){var b=this.chart,a=b.jsonData.markers||{},a=a.connector||a.connectors||
[],c=this.components.markerObjs,d=a.length,e=this.components.connectors,k=function(a){return function(c){var d=c.data,e=d.wrapper;e&&d.options.hoverEffect&&e.attr(d.options._hoverAttrs);q.raiseEvent("connectorrollover",a,b.chartInstance,c)}},f=function(a){return function(c){var d=c.data,e=d.wrapper;e&&d.options.hoverEffect&&e.attr(d.options._defaultAttrs);q.raiseEvent("connectorrollout",a,b.chartInstance,c)}},l=function(a){return function(c){q.raiseEvent("connectorClick",a,b.chartInstance,c)}},r=
b.config.connectorOpts,n={},p,u,x,t,v,w,z,A,B,C,F,E,H;e||(e=this.components.connectors=[]);for(H=0;H<d;H++)if(E=a[H],E.from||E.to)u=c[E.from.toLowerCase()],x=c[E.to.toLowerCase()],u&&x&&(t=a[H].label,n=e[H],!n&&(n=e[H]={}),!n.config&&(p=n.config={}),!n.graphics&&(n.graphics={}),p=n.config=y({},E),p.fromMarker=u,p.toMarker=x,p.link=E.link,p.showTooltip=m(E.showtooltip,r.showTooltip),v=p.tooltext=p.showTooltip?g(E.tooltext,r.tooltext):"",w=p.thickness=g(E.thickness,r.thickness),z=p.color=g(E.color,
r.color),A=p.alpha=g(E.alpha,r.alpha),p.hoverEffect=m(E.showhovereffect,r.showHoverEffect),B=g(E.hovercolor,r.hoverColor,z),C=g(E.hoveralpha,r.hoverAlpha,A),F=g(E.hoverthickness,r.hoverThickness,w),p.dashed=g(E.dashed,r.dashed),p.dashLen=m(E.dashlen,r.dashlen),p.dashGap=m(E.dashgap,r.dashgap),v&&(p.tooltext=v=J(X(v,[3,40,41,42,43],{label:t,fromId:u.config.definition.id,toId:x.config.definition.id,fromLabel:u.config.definition.label,toLabel:x.config.definition.label},void 0))),p.eventArgs={fromMarkerId:u.config.id,
toMarkerId:x.config.id,label:t},p._hoverAttrs={stroke:K({color:B,alpha:C}).toString(),"stroke-width":F},p._defaultAttrs={stroke:K({color:z,alpha:A}).toString(),"stroke-width":w},p.type="line",p.onclick=l(p.eventArgs),p.onmouseover=k(p.eventArgs),p.onmouseout=f(p.eventArgs),t&&(p=n.labelConfig,!p&&(p=n.labelConfig={}),p.type="text",p.text=t,p.align="center",p.valign="middle",p.font=r.font,p.fillcolor=r.fontColor,p.bgcolor=r.labelBgColor,p.bordercolor=r.labelBorderColor,p.tooltext=r.tooltext))},draw:function(){var b=
this.chart,a=this.conf,c=b.components.mapAnnotations,d=this.components.markerObjs,e=b.config,k=e.markerOpts,f=e.scalingParams,e=[],g=[],m,n,q=b.getJobList();this.imageCount=this.imageLoadCount=0;n=c.addGroup({items:g});c=c.addGroup({fillalpha:"100",items:e});this.components.markerGroup=c;this.components.markerLabelGroup=n;a.autoScale=k.autoScale?f.sFactor:1;for(m in d)a=null,k=d[m],f=k.config,f.conIsHidden||(a=this._drawMarkerItem.call(k)),a&&(f._annotationIndex=e.length,k.markerShape=a.markerShape&&
c.addItem(a.markerShape,!1,b),e.push(k.markerShape),k.markerLabel=a.markerLabel&&n.addItem(a.markerLabel,!1,b),g.push(k.markerLabel));this._drawConnectors();q.kdTreeID.push(p.addJob(this._buildKdTree,this,[],u.priorityList.kdTree,!0))},_buildKdTree:function(){var b=this.components.kdArrayMap,a=this.components.markerGroup,c=[],d,h=a&&a.items,k=h&&h.length||0;for(d=0;d<k;d++)a=h[d]._id,b[a]&&c.push(b[a]);this.components.kDTree||(this.components.kDTree=new e(!0));this.components.kDTree._setSearchLimit(Infinity,
Infinity);this.components.kDTree.buildKdTree(c)},_drawMarkerItem:function(){var b=this,a=b.dataset,c=a.chart,d=c.config,e=a.conf,k=d.scalingParams,f=b.config,l=f.options,p=f.definition,n=d.markerOpts,d=n.dataLabels.style,q=l.shapeid,u=l.scale||1,x=l.label||"",t=c.config.scalingParams.scaleFactor*c.baseScaleFactor,c=(l.labelpos||"top").toLowerCase(),v=void 0===f.formattedValue?void 0:f.formattedValue,w=l.tooltext,e=m(p.radius,f.radius,n.radius)*u*e.autoScale||1E-4,p=f.fillColor,z=f.fillAlpha,B=f.fillRatio,
C=f.fillAngle,E=f.borderThickness,F=f.borderColor,H=f.borderAlpha,G,I,K=a.components.kdArrayMap||(a.components.kdArrayMap={}),L=b.config.id;f.autoScale=n.autoScale?t:1;if(q){w=w?J(X(w,[1,2,3],{formattedValue:v,label:x},l)):v?x+n.tooltipSepChar+v:x;void 0!==v&&null!==v?x=x+n.labelSepChar+v:isNaN(u)?u=1:0>u?u=0:5<u&&(u=5);y(l,{x:l.x.toString(),y:l.y.toString(),fillcolor:p,fillalpha:z,fillratio:B,fillangle:C,borderthickness:E,bordercolor:F,borderalpha:H,hovereffect:g(n.showHoverEffect),radius:e.toString(),
link:l.link,showshadow:m(l.showshadow,f.shadow),_markerLabel:x,_markerId:l.id,id:(l.id+"").toLowerCase()});delete l.tooltext;f.tooltext=n.showTooltip?w:!1;t=Number(l.x)*k.sFactor+k.translateX;v=Number(l.y)*k.sFactor+k.translateY;e=l.radius;"triangle"===q?(y(l,{type:"polygon",sides:3,startangle:n.startAngle}),u="polygon",G=3):"diamond"===q?(y(l,{type:"polygon",sides:4,startangle:n.startAngle}),u="polygon",G=4):"arc"===q?(I=.6*e,y(l,{type:"arc",startangle:0,endangle:360,innerradius:I}),u="arc"):"circle"===
q?u=l.type="circle":(G=a.getShapeArgs.call(b),n.dataEnabled&&n.valueToRadius&&void 0!==l.radius?delete G.radius:(!G.radius&&(G.radius=n.radius),G.radius=G.radius*u*f.autoScale),y(l,G),l.id=l._markerId&&l._markerId.toLowerCase(),I=G.innerradius,e=G.radius,u=G.type,G=G.sides);y(l,{hoverfillcolor:g(l.fillhovercolor,n.hoverFillColor,l.fillcolor),hoverfillalpha:g(l.fillhoveralpha,n.hoverFillAlpha,l.fillalpha),hoverfillratio:g(l.fillhoverratio,n.hoverFillRatio,l.fillratio),hoverfillangle:g(l.fillhoverangle,
n.hoverFillAngle,l.fillangle),hoverborderthickness:m(l.borderhoverthickness,n.hoverBorderThickness,l.borderthickness),hoverbordercolor:g(l.borderhovercolor,n.hoverBorderColor,l.bordercolor),hoverborderalpha:g(l.borderhoveralpha,n.hoverBorderAlpha,l.borderalpha)});q={alpha:l.fillalpha,color:l.fillcolor,angle:360-l.fillangle,ratio:l.fillratio};w={alpha:l.hoverfillalpha,color:l.hoverfillcolor,angle:360-l.hoverfillangle,ratio:l.hoverfillratio};l._defaultattrs={fill:A(q),"stroke-width":"0"!==l.showborder?
l.borderthickness:0,stroke:M(l.bordercolor,l.borderalpha)};l._hoverattrs={fill:A(w),"stroke-width":"0"!==l.showborder?l.hoverborderthickness:0,stroke:M(l.hoverbordercolor,l.hoverborderalpha)};"image"===l.type?(l.borderthickness=l.borderthickness||0,l.onload=function(c){var d=this.options,e=c.width;c=c.height;var f={},h=(Number(d.x)-e/(2*k.sFactor))*k.sFactor,d=(Number(d.y)-c/(2*k.sFactor))*k.sFactor,g,f=K[L]||(K[L]={});f.x=h+k.translateX;f.y=d+k.translateY;f.element=b;f.shapeInfo={type:"rect",width:e,
height:c};if(e&&c)for(g in{wrapper:1,tracker:1})this[g]&&this[g].attr({x:h,y:d,width:e,height:c});a.imageLoadCount++;a.imageLoadCount===a.imageCount&&a._buildKdTree()},l.onerror=function(){a.imageLoadCount++;a.imageLoadCount===a.imageCount&&a._buildKdTree()},a.imageCount++):(q=K[L]||(K[L]={}),q.x=t,q.y=v,q.element=b,q.shapeInfo={type:u,sides:G,radius:Number(e)+l.borderthickness/2,innerradius:I});f.drawOptions.shape=l;if(!n.showLabels)return{markerShape:l};I=l.labelpadding||n.labelPadding;c=a._getLabelOptions(c,
I,l);G=c.align;e=c.valign;t=f._labelBaseWidth;u=f._labelBaseHeight;v=f._labelXOffset;q=f._labelYOffset;t=n.labelWrapWidth?n.labelWrapWidth:a.getWrapWidth[G](t,Number(c.x)+v);n=n.labelWrapHeight?n.labelWrapHeight:a.getWrapHeight[e](u,Number(c.y)+q);t>I&&(t-=I);n>I&&(n-=I);f.drawOptions.label=y({type:"text"},{text:x,tooltext:l.tooltext,x:c.x,y:c.y,align:G,valign:c.valign,wrap:1,wrapwidth:t,wrapheight:n,fontsize:d.fontSize/k.sFactor,font:d.fontFamily,fillcolor:d.fontColor});return{markerShape:l,markerLabel:f.drawOptions.label}}},
getHoverFn:function(){var b=this.chart;return function(){var a=this.data("marker"),c=a.markerShape,d=c.options,e=c.bounds,k=d._markerEventArgs,f=c.wrapper,g=c.fillOptions,m=b.config.scalingParams,n=m.translateX,m=m.translateY,a=a.config;f&&d.hovereffect&&("circle"===c.type&&(c={color:d.hoverfillcolor,alpha:d.hoverfillalpha,angle:360-d.hoverfillangle,ratio:d.hoverfillratio,gradientUnits:"objectBoundingBox",radialGradient:g.radialGradient,cx:g.cx,cy:g.cy},d._hoverattrs.fill=A(c)),c=y({},d._hoverattrs),
"image"===f.type&&(delete c.fill,delete c.stroke,delete c["stroke-width"]),f.attr(c));k||(k=d._markerEventArgs={x:e.x1/e.xs,y:e.y1/e.ys,scaledX:e.x1,scaledY:e.y1,chartX:n+e.x1,chartY:m+e.y1,id:d._markerId,label:d._markerLabel});q.raiseEventGroup(a.id,"markerRollOver",k,b.chartInstance,a,void 0,void 0,void 0)}},getHoverOutFn:function(){var b=this.chart;return function(){var a=this.data("marker"),c=a.markerShape,d=c.wrapper,e=c.fillOptions,a=a.config,k=c.options;d&&c.options.hovereffect&&("circle"===
c.type&&(k._defaultattrs.fill=A(e)),e=y({},c.options._defaultattrs),"image"===d.type&&(delete e.fill,delete e.stroke,delete e["stroke-width"]),d.attr(e));q.raiseEventGroup(a.id,"markerRollOut",c.options._markerEventArgs,b.chartInstance,void 0,void 0,void 0)}},getClickFn:function(){var b=this;return function(a){var c=this.data("marker"),d=b.chart,e=d.config.scalingParams,k=e.translateX,e=e.translateY,f=c.markerShape,c=f.options,f=f.bounds,g=c._markerEventArgs;g||(g=c._markerEventArgs={x:f.x1/f.xs,
y:f.y1/f.ys,scaledX:f.x1,scaledY:f.y1,chartX:k+f.x1,chartY:e+f.y1,id:c._markerId,label:c._markerLabel});q.raiseEvent("markerClick",g,d.chartInstance,a)}},highlightPoint:function(b){var a=b.element,c=this.chart,d=c.graphics,e=c.components.paper,k=d.trackerElems||(d.trackerElems={}),f=b.shapeInfo,g,m=b.x,n=b.y,p,q,u;g=c.config.lastHoveredPoint;var t=!1;!1===b?(g=g&&g.shapeInfo.type,(k=k[g])&&k.hide(),c.config.lastHoveredPoint=null):(g=f.type,"circle"===g&&(g="polygon"),k=k[g],"polygon"===g?(p=f.sides||
1,q=f.startAngle,f=f.radius,k?k.attr({polypath:[p,m,n,f,q]}):(k=d.trackerElems[g]=e.polypath(p,m,n,f,q),t=!0)):"rect"===g?(q=f.width,f=f.height,k?k.attr({x:m,y:n,width:q,height:f}):(k=d.trackerElems[g]=e.rect(m,n,q,f),t=!0)):"arc"===g&&(p=a.markerShape.bounds.innerR,u=a.markerShape.bounds.angles,q=u.start*Y,u=u.end*Y,f=f.radius,k?k.attr({ringpath:[m,n,f,p,q,u]}):(k=d.trackerElems[g]=e.ringpath(m,n,f,p,q,u),t=!0)),c.config.lastHoveredPoint=b,t&&(k.attr({fill:Z,stroke:Z}).click(this.getClickFn()).hover(this.getHoverFn(),
this.getHoverOutFn()),k.trackTooltip(!0)),k.show().tooltip(a.config.tooltext).data("marker",a))},_drawConnectors:function(){var b=this.chart,a=this.components.connectors,c=a.length,d=b.config.scalingParams,e=b.config.connectorOpts,g=e.showLabels,f=b.components.mapAnnotations,l,m=[],n=[],p,q,u,t,v=[];v.push({id:"connectorLabels",fillalpha:"100",items:n});v.push({id:"connectors",fillalpha:"100",items:m});for(l=0;l<c;l++)a[l]&&(q=a[l].config.fromMarker.config,t=a[l].config.toMarker.config,p=q.options.x,
q=q.options.y,u=t.options.x,t=t.options.y,a[l].config.x=p,a[l].config.y=q,a[l].config.tox=u,a[l].config.toy=t,m.push(a[l].config),a[l].labelConfig&&g&&(a[l].labelConfig.x=((Number(p)+Number(u))/2).toString(),a[l].labelConfig.y=((Number(q)+Number(t))/2).toString(),a[l].labelConfig.fontsize=e.fontSize/(d.scaleFactor*b.baseScaleFactor),n.push(a[l].labelConfig)));f.addGroup(v[0]);f.addGroup(v[1])},getShapeArgs:function(){var b=this.config,a=y({},this.shapeObj),c;b.autoScale=1;return a?("polygon"===a.type?
3>a.sides?a.type="circle":a.startangle=b.startAngle:"arc"===a.type&&(c=(a.radius||b.markerRadius)*b.autoScale,a.radius=c,a.innerradius=a.innerradius&&a.innerradius*b.autoScale||.6*c),a):null},_getLabelOptions:function(b,a,c,d,e){var g,f=b&&b.toLowerCase();this.getLabelAlignment[f]||(f="center");b=Number(c.x);g=Number(c.y);c=void 0===d||void 0===e?c.radius||0:/^(top|bottom)$/ig.test(f)&&.5*e||/^(left|right)$/ig.test(f)&&.5*d||0;c=Number(c)+Number(a);return this.getLabelAlignment[f](b,g,c)},getLabelAlignment:{top:function(b,
a,c){return{x:b.toString(),y:(a-c).toString(),align:"center",valign:"top"}},left:function(b,a,c){return{x:(b-c).toString(),y:a.toString(),align:"right",valign:"middle"}},right:function(b,a,c){return{x:(b+c).toString(),y:a.toString(),align:"left",valign:"middle"}},bottom:function(b,a,c){return{x:b.toString(),y:(a+c).toString(),align:"center",valign:"bottom"}},center:function(b,a){return{x:b.toString(),y:a.toString(),align:"center",valign:"middle"}}},getWrapWidth:{right:function(b,a){return a},left:function(b,
a){return b-a},center:function(b,a){return 2*H(a,b-a)}},getWrapHeight:{top:function(b,a){return a},middle:function(b,a){return 2*H(a,b-a)},bottom:function(b,a){return b-a}},addMarkerItem:function(b){var a=this.components.markerObjs,c=this.components.shapeObjs,d=this.components.markerGroup,e=this.components.markerLabelGroup,g,f;if((f=b.id.toLowerCase())&&!a[f]){delete b.value;this.imageLoadCount=0;b=this._initializeMarkerItem(f,b,null);b.dataset=this;if(g=b.config.options.shapeid)b.shapeObj=c[g&&g.toLowerCase()];
a[f]=b;a=this._drawMarkerItem.call(b);d&&e&&(b.markerShape=a.markerShape&&d.addItem(a.markerShape,!0),b.markerLabel=a.markerLabel&&e.addItem(a.markerLabel,!0));this._buildKdTree()}},updateMarkerItem:function(b,a){var c=this.chart.components.mapAnnotations,d,e=this.components.markerObjs[b];e&&(d=e.config.options,y(d,a),this.imageLoadCount=0,d=this._drawMarkerItem.call(e).markerShape,this._buildKdTree(),c.update(b,d))},_removeMarkerItem:function(b){var a=this.components,c=a.markerObjs,d=c[b],a=a.kdArrayMap,
e;d&&(e=d.markerShape,d=d.markerLabel,e&&e.destroy(),d&&d.destroy(),delete a[b],this._buildKdTree());delete c[b]},getElement:function(b){if(this.components.kDTree)return this.components.kDTree.getNeighbour(b)}},"Entities"])},[3,2,0,"release"]])});
