/*
 FusionCharts JavaScript Library - Tree Map Chart
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.12.0
*/
(function(O){"object"===typeof module&&"undefined"!==typeof module.exports?module.exports=O:O(FusionCharts)})(function(O){O.register("module",["private","modules.renderer.js-treemap",function(){function ba(a){return a?a.replace(/^#*/,"#"):"#E5E5E5"}function x(a,b,d){this.label=a;this.value=parseFloat(b,10);this.colorValue=parseFloat(d,10);this.prev=this.next=void 0;this.meta={}}function P(){this._b=[];this._css=void 0;this.rangeOurEffectApplyFn=function(){};this.statePointerLow={value:void 0,index:void 0};
this.statePointerHigh={value:void 0,index:void 0}}var ja,ka,ha,la,J=this.hcLib,ca=J.chartAPI,V=Math,Y=V.max,ma=V.round,sa=V.tan,na=V.min,ta=V.PI,oa=J.extend2,Z=this.window,ua=J.parsexAxisStyles,V=J.Raphael,pa=J.graphics,da=pa.convertColor,qa=pa.getLightColor,z=this.raiseEvent,y=J.pluckNumber,K=J.pluck,va=J.each,ea=J.BLANKSTRING,wa="rgba(192,192,192,"+(/msie/i.test(Z.navigator.userAgent)&&!Z.opera?.002:1E-6)+")",Z=!J.CREDIT_REGEX.test(Z.location.hostname),ra=J.plotEventHandler,fa=J.schedular,xa=J.preDefStr.DEFAULT;
V.addSymbol({backIcon:function(a,b,d){--d;var c=b+d,g=c-d/2,p=a+d,r=g-d;return["M",a,b-d,"L",a-d,b,a,c,a,g,p,g,p,r,p-d,r,"Z"]},homeIcon:function(a,b,d){--d;var c=2*d,g=a-d,p=g+c/6,r=b+d,A=p+c/4,m=r-d/2,k=A+c/6,t=m+d/2,n=k+c/4,f=t-d;return["M",a,b-d,"L",g,b,p,b,p,r,A,r,A,m,k,m,k,t,n,t,n,f,n+c/6,f,"Z"]}});x.prototype.constructor=x;x.prototype.getCSSconf=function(){return this.cssConf};x.prototype.getPath=function(){return this.path};x.prototype.setPath=function(){var a=this.getParent();this.path=(a?
a.getPath():[]).concat(this)};x.prototype.addChild=function(a){a instanceof x&&(this.next=this.next||[],[].push.call(this.next,a),a.setParent(this));return this.next};x.prototype.getChildren=function(){return this.next};x.prototype.addChildren=function(a,b){var d=this.getChildren()||(this.next=[]),c=d.length;b||(b=c-1);d.splice(b>c-1?c-1:0>b?0:b,0,a);a.setParent(this)};x.prototype.getDepth=function(){return this.meta.depth};x.prototype.isLeaf=function(a){return(a?this.getDepth()<a:!0)&&this.next};
x.prototype.setParent=function(a){a instanceof x&&(this.prev=a);return this};x.prototype.getSiblingCount=function(a){var b,d=0,c=this;if(this instanceof x){b=this.getParent();if(a){for(;c;)(c=c.getSibling(a))&&(d+=1);return d}if(b)return b.getChildren().length}};x.prototype.getParent=function(){return this.prev};x.prototype.getLabel=function(){return this.label};x.prototype.getValue=function(){return this.value};x.prototype.setValue=function(a,b){this.value=b?this.value+a:a};x.prototype.getColorValue=
function(){return this.colorValue};x.prototype.getSibling=function(a){a=a.toLowerCase();var b=this.getParent(),d=this.getLabel(),c,g;if(b)for(b=b.getChildren(),c=0;c<b.length;c++)if(g=b[c],g=g.getLabel(),g===d)switch(a){case "left":return b[c-1];case "right":return b[c+1]}};x.prototype.setMeta=function(a,b){this.meta[a]=b};x.prototype.setDepth=function(a){this.meta.depth=a};x.prototype.getMeta=function(a){return a?this.meta[a]:this.meta};P.prototype.constructor=P;P.prototype.resetPointers=function(){this.statePointerLow=
{value:void 0,index:void 0};this.statePointerHigh={value:void 0,index:void 0}};P.prototype.setRangeOutEffect=function(a,b){this._css=a;this.rangeOurEffectApplyFn=b};P.prototype.addInBucket=function(a){var b=this._b,d=a.getColorValue(),c=0,g=b.length-1;if(d){a:{for(var p,r;c<=g;)if(p=(c+g)/2|0,r=b[p],r=r.getColorValue(),r<d)c=p+1;else if(r>d)g=p-1;else{d=p;break a}d=~g}b.splice(Math.abs(d),0,a)}};P.prototype.moveLowerShadePointer=function(a){var b=this._b,d,c,g,p=this.statePointerLow;d=p.index;c=p.value;
var r=!1;d=void 0!==d?d:0;c=void 0!==c?c:Number.NEGATIVE_INFINITY;if(a!==c){if(c<=a){for(;;){g=(c=b[d++])?c.getColorValue():0;if(a<g||!c)break;r=!0;c.rangeOutEffect=this._css;this.rangeOurEffectApplyFn.call(c,this._css)}d=r?d-2:d-1}else{for(;;){g=(c=b[d--])?c.getColorValue():0;if(a>=g||!c)break;c.cssConf=c.cssConf||{};r=!0;delete c.rangeOutEffect;c.cssConf.opacity=1;this.rangeOurEffectApplyFn.call(c,c.cssConf)}d=r?d+2:d+1}p.index=d;p.value=a}};P.prototype.moveHigherShadePointer=function(a){var b=
this._b,d=b.length,c,g,p=this.statePointerHigh;g=p.index;c=p.value;var r=!1,d=void 0!==g?g:d-1;c=void 0!==c?c:Number.POSITIVE_INFINITY;if(a!==c){if(c>a){for(;;){g=(c=b[d--])?c.getColorValue():0;if(a>=g||!c)break;r=!0;c.rangeOutEffect=this._css;this.rangeOurEffectApplyFn.call(c,this._css)}d=r?d+2:d+1}else{for(;;){g=(c=b[d++])?c.getColorValue():0;if(a<g||!c)break;c.cssConf=c.cssConf||{};r=!0;delete c.rangeOutEffect;c.cssConf.opacity=1;this.rangeOurEffectApplyFn.call(c,c.cssConf)}d=r?d-2:d-1}p.index=
d;p.value=a}};ca("treemap",{friendlyName:"TreeMap",standaloneInit:!0,hasGradientLegend:!0,creditLabel:Z,defaultDatasetType:"treemap",enableMouseOutEvent:!0,applicableDSList:{treemap:!0},_mouseEvtHandler:function(a){var b=a.data,d=b.chart,b=b.mouseTracker,c=d.config,g=c.canvasLeft,p=c.canvasRight,r=c.canvasBottom,A=c.canvasTop,m=c.datasetOrder||d.components.dataset,c=J.getMouseCoordinate(d.linkedItems.container,a.originalEvent,d),k=c.chartX,t=c.chartY,n,f,Q=!1,l=m.length,q,w=b._lastDatasetIndex,c=
b._lastPointIndex;if(k>g&&k<p&&t>A&&t<r||d.config.plotOverFlow)for(;l--&&!Q;)(n=m[l])&&(f=n._getHoveredPlot&&n._getHoveredPlot(k,t))&&f.hovered&&(Q=!0,f.datasetIndex=l,q=b._getMouseEvents(a,f.datasetIndex,f.pointIndex));(!Q||q&&q.fireOut)&&void 0!==w&&(delete b._lastDatasetIndex,delete b._lastPointIndex,m[w]&&m[w]._firePlotEvent&&m[w]._firePlotEvent("mouseout",c,a));if(Q)for(d=q.events&&q.events.length,b._lastDatasetIndex=f.datasetIndex,c=b._lastPointIndex=f.pointIndex,f=0;f<d;f+=1)n&&n._firePlotEvent&&
n._firePlotEvent(q.events[f],c,a)},addData:function(){var a=this._ref.algorithmFactory,b=Array.prototype.slice.call(arguments,0);b.unshift("addData");b.unshift(this._getCleanValue());a.realTimeUpdate.apply(this,b)},removeData:function(){var a=this._ref.algorithmFactory,b=Array.prototype.slice.call(arguments,0);b.unshift("deleteData");b.unshift(this._getCleanValue());a.realTimeUpdate.apply(this,b)},_createToolBox:function(){var a,b,d,c,g=this.components;a=g.chartMenuBar;b=g.actionBar;a&&a.drawn||b&&
b.drawn||(ca.mscartesian._createToolBox.call(this),a=g.tb,b=a.getAPIInstances(a.ALIGNMENT_HORIZONTAL),d=b.Symbol,b=(g.chartMenuBar||g.actionBar).componentGroups[0],c=new d("backIcon",!1,(a.idCount=a.idCount||0,a.idCount++),a.pId),a=new d("homeIcon",!1,a.idCount++,a.pId),b.addSymbol(a,!0),b.addSymbol(c,!0),g.toolbarBtns={back:c,home:a})},_getCleanValue:function(){var a=this.components.numberFormatter;return function(b){return a.getCleanValue(b)}},_createDatasets:function(){var a=this.components,b=
this.jsonData,d=b.dataset,d=b.data||d&&d[0].data,c=this.defaultDatasetType,g=[];d&&d.length||this.setChartMessage();va(d,function(a){a.vline||g.push(a)});b={data:g};this.config.categories=g;a=a.dataset||(a.dataset=[]);d?c&&(d=O.get("component",["dataset",c]))&&(a[0]?(a[0].JSONData=g[0],a[0].configure()):(this._dsInstance=d=new d,a.push(d),d.chart=this,d.init(b))):this.setChartMessage()},init:function(){var a={},b={},d={};this._ref={afAPI:ja(a,b,d),algorithmFactory:ka(a,b,d),containerManager:la(a,
b,d),treeOpt:ha};ca.guageBase.init.apply(this,arguments)}},ca.guageBase,{enablemousetracking:!0});O.register("component",["dataset","TreeMap",{type:"treemap",pIndex:2,customConfigFn:"_createDatasets",init:function(a){this.JSONData=a.data[0];this.components={};this.conf={};this.graphics={elemStore:{rect:[],label:[],highlight:[],hot:[],polypath:[]}};this.configure()},configure:function(){var a,b=this.chart,d=b.components,c=this.conf,b=b.jsonData.chart;c.metaTreeInf={};c.algorithm=(b.algorithm||"squarified").toLowerCase();
c.horizontalPadding=y(b.horizontalpadding,5);c.horizontalPadding=0>c.horizontalPadding?0:c.horizontalPadding;c.verticalPadding=y(b.verticalpadding,5);c.verticalPadding=0>c.verticalPadding?0:c.verticalPadding;c.showParent=y(b.showparent,1);c.showChildLabels=y(b.showchildlabels,0);c.highlightParentsOnHover=y(b.highlightparentsonhover,0);c.defaultParentBGColor=K(b.defaultparentbgcolor,void 0);c.defaultNavigationBarBGColor=K(b.defaultnavigationbarbgcolor,c.defaultParentBGColor);c.showTooltip=y(b.showtooltip,
1);c.baseFontSize=y(b.basefontsize,10);c.baseFontSize=1>c.baseFontSize?1:c.baseFontSize;c.labelFontSize=y(b.labelfontsize,void 0);c.labelFontSize=1>c.labelFontSize?1:c.labelFontSize;c.baseFont=K(b.basefont,"Verdana, Sans");c.labelFont=K(b.labelfont,void 0);c.baseFontColor=K(b.basefontcolor,"#000000").replace(/^#?([a-f0-9]+)/ig,"#$1");c.labelFontColor=K(b.labelfontcolor,void 0);c.labelFontColor&&(c.labelFontColor=c.labelFontColor.replace(/^#?([a-f0-9]+)/ig,"#$1"));c.labelFontBold=y(b.labelfontbold,
0);c.labelFontItalic=y(b.labelfontitalic,0);c.plotBorderThickness=y(b.plotborderthickness,1);c.plotBorderThickness=0>c.plotBorderThickness?0:5<c.plotBorderThickness?5:c.plotBorderThickness;c.plotBorderColor=K(b.plotbordercolor,"#000000").replace(/^#?([a-f0-9]+)/ig,"#$1");c.tooltipSeparationCharacter=K(b.tooltipsepchar,",");c.plotToolText=K(b.plottooltext,"");c.parentLabelLineHeight=y(b.parentlabellineheight,12);c.parentLabelLineHeight=0>c.parentLabelLineHeight?0:c.parentLabelLineHeight;c.labelGlow=
y(b.labelglow,1);c.labelGlowIntensity=y(b.labelglowintensity,100)/100;c.labelGlowIntensity=0>c.labelGlowIntensity?0:1<c.labelGlowIntensity?1:c.labelGlowIntensity;c.labelGlowColor=K(b.labelglowcolor,"#ffffff").replace(/^#?([a-f0-9]+)/ig,"#$1");c.labelGlowRadius=y(b.labelglowradius,2);c.labelGlowRadius=0>c.labelGlowRadius?0:10<c.labelGlowRadius?10:c.labelGlowRadius;c.btnResetChartTooltext=K(b.btnresetcharttooltext,"Back to Top");c.btnBackChartTooltext=K(b.btnbackcharttooltext,"Back to Parent");c.rangeOutBgColor=
K(b.rangeoutbgcolor,"#808080").replace(/^#?([a-f0-9]+)/ig,"#$1");c.rangeOutBgAlpha=y(b.rangeoutbgalpha,100);c.rangeOutBgAlpha=1>c.rangeOutBgAlpha||100<c.rangeOutBgAlpha?100:c.rangeOutBgAlpha;a=y(b.maxdepth);c.maxDepth=void 0!==a?Y(a,1):void 0;a=c.showNavigationBar=y(b.shownavigationbar,1);c.slicingMode=K(b.slicingmode,"alternate");c.navigationBarHeight=y(b.navigationbarheight);c.navigationBarHeightRatio=y(b.navigationbarheightratio);c.navigationBarBorderColor=K(b.navigationbarbordercolor,c.plotBorderColor).replace(/^#?([a-f0-9]+)/ig,
"#$1");c.navigationBarBorderThickness=a?y(b.navigationbarborderthickness,c.plotBorderThickness):0;c.seperatorAngle=y(b.seperatorangle)*(ta/180);d.postLegendInitFn({min:0,max:100});c.isConfigured=!0},_getHoveredPlot:function(a,b){var d,c;for(c=(this.kdTree||[]).length;c--&&(!this.kdTree[c]||!(d=this.kdTree[c].searchTreemap(a,b))););if(d)return this.pointObj=d,{pointIndex:d.i||d.index,hovered:!0,pointObj:d}},kdTreeAbs:function(a){function b(a,b,c){return a>=b&&a<=c}function d(a,b,u,v){var e={},h;h=
v?"y":"x";if(0!==a.length){if(b===u)return e.point=a[b],e;if(1===u-b)return a[b][h]>a[u][h]?(e.point=a[b],e.left={point:a[u]}):(e.point=a[u],e.left={point:a[b]}),e;h=b+u>>1;v?g(a,h,b,u):c(a,h,b,u);e.point=a[h];e.left=d(a,b,h-1,!v);e.right=d(a,h+1,u,!v);return e}}function c(a,b,u,d){for(var e,h,B,C,l;d>u;){600<d-u&&(e=d-u+1,h=b-u+1,B=f(e),C=.5*Q(2*B/3),l=.5*t(B*C*(e-C)/e)*(0>h-e/2?-1:1),B=m(u,k(b-h*C/e+l)),e=n(d,k(b+(e-h)*C/e+l)),c(a,b,B,e));e=a[b];h=u;C=d;p(a,u,b);for(a[d].x>e.x&&p(a,u,d);h<C;){p(a,
h,C);h++;for(C--;a[h].x<e.x;)h++;for(;a[C].x>e.x;)C--}a[u].x===e.x?p(a,u,C):(C++,p(a,C,d));C<=b&&(u=C+1);b<=C&&(d=C-1)}}function g(a,b,c,d){for(var e,h,B,l,G;d>c;){600<d-c&&(e=d-c+1,h=b-c+1,B=f(e),l=.5*Q(2*B/3),G=.5*t(B*l*(e-l)/e)*(0>h-e/2?-1:1),B=m(c,k(b-h*l/e+G)),e=n(d,k(b+(e-h)*l/e+G)),g(a,b,B,e));e=a[b];h=c;l=d;p(a,c,b);for(a[d].y>e.y&&p(a,c,d);h<l;){p(a,h,l);h++;for(l--;a[h].y<e.y;)h++;for(;a[l].y>e.y;)l--}a[c].y===e.y?p(a,c,l):(l++,p(a,l,d));l<=b&&(c=l+1);b<=l&&(d=l-1)}}function p(a,b,c){var d=
a[b];a[b]=a[c];a[c]=d}var r=a&&a[0]&&a[0].plotDetails.rect||5,A,m=Math.max,k=Math.floor,t=Math.sqrt,n=Math.min,f=Math.log,Q=Math.exp,l=Math.pow;A={};a=a||[];for(A=a.length;A--;)a[A].r>r&&(r=a[A].r),a[A].x=+a[A].plotDetails.rect.x,a[A].y=+a[A].plotDetails.rect.y;A={tree:d(a,0,a.length-1,!1),search:function(a,c){function d(e){var u=b(a,e.x1,e.x2)&&b(c,e.y1,e.y2),f;f=e.point.y;f=t(l(a-e.point.x,2)+l(c-f,2));h?u?g?e.point.i>h.point.i&&(h=e,g=u,n=f):(h=e,g=u,n=f):!g&&f<n&&(h=e,g=u,n=f):(h=e,g=u,n=f)}function f(a){a&&
a.point&&(b(a.point.x,B,C)&&b(a.point.y,k,m)&&d(a),B<=a.point.x&&e(a.left),C>=a.point.x&&e(a.right))}function e(a){a&&a.point&&(b(a.point.x,B,C)&&b(a.point.y,k,m)&&d(a),k<=a.point.y&&f(a.left),m>=a.point.y&&f(a.right))}var h,B=a-r,C=a+r,k=c-r,m=c+r,g=!1,n=0;f(this.tree);return h&&h.point||h},searchTreemap:function(a,b){var c,d=function(e,h){if(e&&e.point){var l=e.point.x,f=l+e.point.plotDetails.rect.width,t=e.point.y,k=t+e.point.plotDetails.rect.height;e.point.x2=f;e.point.y2=k;a>=l&&a<=f&&b>=t&&
b<=k&&(l=e.point,c?l.i>c.i&&(c=l):c=l);d(e.left,!h);d(e.right,!h)}};d(this.tree,!1);return c}};a.sort(function(a,b){return a.i-b.i});return A},kdTreePartioning:function(){var a=this.chart.config.trackerConfig,b,d=[];for(b=a.length;b--;)a[b].i=b,void 0===d[a[b].node.meta.depth]&&(d[a[b].node.meta.depth]=[]),d[a[b].node.meta.depth].push(a[b]);this.kdTree=[];for(b=d.length;b--;)this.kdTree[b]=this.kdTreeAbs&&this.kdTreeAbs(d[b])},_rolloverResponseSetter:function(a,b,d){var c=b.getData()||{};b&&(b.attr(c.setRolloverAttr),
ra.call(b,a,d,"DataPlotRollOver"))},_rolloutResponseSetter:function(a,b,d){var c=b.getData()||{};b&&(b.attr(c.setRolloutAttr),ra.call(b,a,d,"DataPlotRollOut"))},_firePlotEvent:function(a,b,d){var c=this.conf,g=this.chart,p=g.getJobList(),r=g.components.paper;b=this.chart.config.trackerConfig[b||0];var A=g.graphics.trackerGroup,m=b&&b.node&&b.node.plotItem,k=b&&b.evtFns&&b.evtFns.tooltip[0],t=g.components.paper.canvas.style,n=J.toolTip;d=d.originalEvent;var f=this.graphics.singleTracker,Q=this.pointObj.plotDetails,
l=Q&&Q.rect,c=c.highlightParentsOnHover,q=b&&b.node.path,w=(q=q&&q[q.length-2])&&q.rect;f||(f=this.graphics.singleTracker=r.rect(A));m?c&&q?f.attr({x:w.x,y:w.y,width:w.width,height:w.height,stroke:"rgba(255,255,255,0)"}):(Q?f.attr({x:l.x||0,y:l.y||0,width:l.width||0,height:l.height||0,stroke:"rgba(255,255,255,0)"}):f.attr({x:0,y:0,width:0,height:0,stroke:"rgba(255,255,255,0)"}),f.toFront()):m=b&&b.node.dirtyNode.plotItem;if(m)switch(a){case "mouseover":b.evtFns.hover[0](f);k&&(n.setStyle(r),n.setPosition(d),
n.draw(k,r));t.cursor="pointer";break;case "mouseout":f.attr({x:0,y:0,width:0,height:0,stroke:"#ffffff","stroke-width":"0px"});n.hide();t.cursor=xa;f.toFront();this._rolloutResponseSetter(g,m,d);break;case "click":b&&b.evtFns&&b.evtFns.click&&b.evtFns.click[0]();k&&(n.setStyle(r),n.setPosition(d),n.draw(k,r));p.trackerDrawID.push(fa.addJob(this.kdTreePartioning,this,[],J.priorityList.tracker));break;case "mousemove":k&&(n.setPosition(d),n.draw(k,r))}},draw:function(){var a=this.conf,b=this.chart,
d=b.config.trackerConfig,c=b.getJobList(),g=b.config,p=b.components,r=g.canvasLeft,A=g.canvasRight,m=g.canvasBottom,k=g.canvasTop,t=p.paper,n=b.jsonData.chart,f=b.graphics,Q=f.trackerGroup,l,q,w,u,v,g=a.metaTreeInf,e=this.graphics.elemStore,h={},B,C,G=["fontFamily","fontSize","fontWeight","fontStyle"],X={},R,p=p.gradientLegend,aa,x=b._ref,W=x.afAPI.visibilityController,E=b.get("config","animationObj"),H=E.duration||0,F=E.dummyObj,D=E.animObj,y=E.animType,S,E=x.containerManager,x=x.algorithmFactory,
ga;d&&(d.length=0);S=ua({},{},n,{fontFamily:"Verdana,sans",fontSize:"10px"});d=0;for(n=G.length;d<n;d++)ga=G[d],ga in S&&(X[ga]=S[ga]);for(q in e){G=e[q];d=0;for(n=G.length;d<n;d++)(S=G[d])&&S.remove&&S.remove();G.length=0}E.remove();l=f.datasetGroup=f.datasetGroup||t.group("dataset");q=f.datalabelsGroup=(f.datalabelsGroup||t.group("datalabels").insertAfter(l)).css(X);w=f.lineHot=f.lineHot||t.group("line-hot",Q);u=f.labelHighlight=f.labelHighlight||t.group("labelhighlight",q);v=f.floatLabel=f.floatLabel||
t.group("labelfloat",q).insertAfter(u);a.colorRange=p.colorRange;g.effectiveWidth=A-r;g.effectiveHeight=m-k;g.startX=r;g.startY=k;B=g.effectiveWidth/2;C=g.effectiveHeight/2;B=g.effectiveWidth/2;C=g.effectiveHeight/2;h.drawPolyPath=function(a,b){var c,d;c=(h.graphicPool(!1,"polyPathItem")||(d=t.path(l))).attr({path:a._path}).animateWith(F,D,{path:a.path},H,y);c.css(b);d&&e.polypath.push(d);return c};h.drawRect=function(a,b,c,d){var u,f,q={},w={},v;for(u in a)f=a[u],0>f&&(a[u]=0,w.visibility="hidden");
oa(q,a);q.x=B;q.y=C;q.height=0;q.width=0;R=h.graphicPool(!1,"plotItem")||(v=t.rect(l));R.attr(c&&(c.x||c.y)&&c||q);R.attr(d);R.animateWith(F,D,a,H,y,W.controlPostAnimVisibility);R.css(b).toFront();R.css(w);v&&e.rect.push(v);return R};h.drawText=function(b,c,d,l,q){var f={},w,k,m=h.graphicPool(!1,"labelItem")||(w=t.text(v)),g=h.graphicPool(!1,"highlightItem")||(k=t.text(u)),n=d.textAttrs;d=d.highlightAttrs;oa(f,n);delete f.fill;f["stroke-linejoin"]="round";m.attr({x:l.x||B,y:l.y||C,fill:"#000000"}).css(n);
m.attr(q);b=0>c.x||0>c.y?ea:b;m.animateWith(F,D,{text:b,x:c.x,y:c.y},H,y);g.attr({text:b,x:l.x||B,y:l.y||C,stroke:a.labelGlow?"#ffffff":wa}).css(f).css(d);g.attr(q);g.animateWith(F,D,{x:c.x,y:c.y},H,y);e.label.push(w);e.highlight.push(k);return{label:m,highlightMask:g}};h.drawHot=function(a,b){var c;c=a.plotItem||{};var d=a.rect,h,l,q;for(l in d)q=d[l],0>q&&(d[l]=0);c=c.tracker=t.rect(w).attr(d).attr({cursor:"pointer",fill:"rgba(255, 255, 255, 0)",stroke:"none"});for(h in b)d=b[h],c[h].apply(c,d);
e.hot.push(c);return c};h.disposeItems=function(a,b){var c,e,d,l=b||"plotItem labelItem hotItem highlightItem polyPathItem pathlabelItem pathhighlightItem stackedpolyPathItem stackedpathlabelItem stackedpathhighlightItem".split(" ");for(c=0;c<l.length;c+=1)d=l[c],(e=a[d])&&h.graphicPool(!0,d,e,a.rect),e&&e.hide(),a[d]=void 0};h.disposeChild=function(){var a,c=function(){return a.disposeItems},b=function(a,e){var d,h;c(a);for(d=0;d<(a.getChildren()||[]).length;d++)h=a.getChildren(),d=b(h[d],d);return e};
return function(e){var d=e.getParent();a||(a=this,c=c());d?a.disposeChild(d):b(e,0)}}();h.graphicPool=function(){var a={};return function(c,b,e){var d=a[b];d||(d=a[b]=[]);"hotItem"!==b&&"pathhotItem"!==b||e.remove();if(c)d.push(e);else if(c=d.splice(0,1)[0])return c.show(),c}}();h.disposeComplimentary=function(a){var c,b;c=a.getParent();var e=a.getSiblingCount("left");c&&(b=c.getChildren(),c=b.splice(e,1)[0],this.disposeChild(a),b.splice(e,0,c));this.removeLayers()};h.removeLayers=function(){var a,
c,b,d;b=e.hot;d=b.length;for(a=0;a<d;a++)(c=b[a])&&c.remove();b.length=0};x.init(a.algorithm,!0,a.maxDepth);b=x.plotOnCanvas(this.JSONData,void 0,b._getCleanValue());E.init(this,g,h,void 0,b);E.draw();aa=x.applyShadeFiltering({fill:a.rangeOutBgColor,opacity:.01*a.rangeOutBgAlpha},function(a){this.plotItem&&this.plotItem.css(a)});p&&p.enabled&&(p.resetLegend(),p.clearListeners());p.notifyWhenUpdate(function(a,c){aa.call(this,{start:a,end:c})},this);a.isConfigured=!1;c.trackerDrawID.push(fa.addJob(this.kdTreePartioning,
this,[],J.priorityList.tracker))}}]);ja=function(a,b,d){function c(a,c,b){this.node=a;this.bucket=c?new P:void 0;this.cleansingFn=b}var g,p,r,A;c.prototype.get=function(){var a=this.order,c=this.bucket,b=this.cleansingFn;return function f(d,l){var q,w,u,v;w=["label","value","data","svalue"];if(d)for(v in q=new x(d.label,b(d.value),b(d.svalue)),u=d.data||[],0===u.length&&c&&c.addInBucket(q),q.setDepth(l),d)-1===w.indexOf(v)&&q.setMeta(v,d[v]);a&&(u=a(u));for(w=0;w<u.length;w++)v=u[w],v=f(v,l+1),q.addChild(v);
return q}(this.node,0)};c.prototype.getBucket=function(){return this.bucket};c.prototype.getMaxDepth=function(){return p};g=function(a,c){function b(a){this.iterAPI=a}var d=c&&c.exception,f,g;b.prototype.constructor=b;b.prototype.initWith=function(a){return this.iterAPI(a)};f=(new b(function(a){var c=a,b=[],f=!1;b.push(c);return{next:function(a){var c,h;if(!f){c=b.shift();if(d&&c===d&&(c=b.shift(),!c)){f=!0;return}(h=(a=void 0!==a?c.getDepth()>=a?[]:c.getChildren():c.getChildren())&&a.length||0)&&
[].unshift.apply(b,a);0===b.length&&(f=!0);return c}},reset:function(){f=!1;c=a;b.length=0;b.push(c)}}})).initWith(a);g=(new b(function(a){var c=a,b=[],d=[],f=!1;b.push(c);d.push(c);return{next:function(){var a,c,d;if(!f)return c=b.shift(),(d=(a=c.getChildren())&&a.length||0)&&[].push.apply(b,a),0===b.length&&(f=!0),c},nextBatch:function(){var a,c;if(!f)return a=d.shift(),(c=(a=a.getChildren())&&a.length||0)&&[].push.apply(d,a),0===b.length&&(f=!0),a},reset:function(){f=!1;c=a;b.length=0;b.push(c)}}})).initWith(a);
return{df:f,bf:g}};A=function(){function a(){this.con={}}var c={},b;a.prototype.constructor=a;a.prototype.get=function(a){return this.con[a]};a.prototype.set=function(a,c){this.con[a]=c};a.prototype["delete"]=function(a){return delete this.con[a]};return{getInstance:function(d){var f;return(f=c[d])?b=f:b=c[d]=new a}}}();b=function(){var a=[],c,b=!1,d={visibility:"visible"};return{controlPreAnimVisibility:function(d,n){var l,q,w;if(d){for(q=d;;){q=q.getParent();if(!q)break;l=q}l=g(l,{exception:d});
for(l=l.df;;){q=l.next();if(!q)break;w=q.overAttr||(q.overAttr={});w.visibility="hidden";a.push(q)}c=n||d.getParent();b=!1;return a}},displayAll:function(d){var n;if(d){d=g(d.getParent()||d);for(d=d.df;;){n=d.next();if(!n)break;n=n.overAttr||(n.overAttr={});n.visibility="visible"}c=void 0;a.length=0;b=!1}},controlPostAnimVisibility:function(){var f,r;if(!b&&(b=!0,c)){r=g(c);for(r=r.df;;){f=r.next(p);if(!f)break;if(f=f.dirtyNode)f&&f.plotItem.attr(d),(f=f&&f.textItem)&&f.label&&f.label.attr(d),f&&
f.label&&f.highlightMask.attr(d)}c=void 0;a.length=0}}}}();a.AbstractTreeMaker=c;a.iterator=g;a.initConfigurationForlabel=function(a,c,b){var d=a.x,f=a.y,g=c/2,l=b.showParent?0:1,q=b.showChildLabels;return function(a,u,v,e){v=!1;var h={x:void 0,y:void 0,width:void 0,height:void 0},B={},C=0,m={},r={},R,m=a.meta;if(a)return a.isLeaf(p)||(v=!0),B.label=a.getLabel(),h.width=u.width-2*d,h.x=u.x+u.width/2,a=u.height-2*f,!v&&a<c&&(h.height=-1),!e&&v?(h.height=q?h.height?h.height:u.height-2*f:-1,h.y=u.y+
u.height/2):l?(h.y=-1,c=f=0,R="hidden"):(h.height=h.height?h.height:c,h.y=u.y+f+g),C+=2*f,C+=c,B.rectShiftY=C,B.textRect=h,b.labelGlow?(r["stroke-width"]=b.labelGlowRadius,r.opacity=b.labelGlowIntensity,r.stroke=b.labelGlowColor,r.visibility="hidden"===R?"hidden":"visible"):r.visibility="hidden",m={fill:m&&m.fontcolor&&ba(m.fontcolor)||b.labelFontColor||b.baseFontColor,visibility:R},{conf:B,attr:m,highlight:r}}};a.context=A;a.mapColorManager=function(a,c,b){var d=ba(b?a.defaultNavigationBarBGColor:
a.defaultParentBGColor);return function(b,g,l){g={};var q=b.cssConf,w=b.meta,w=w.fillcolor?ba(w.fillcolor):void 0,u=b.getParent(),v;v=b.getColorValue();a.isLegendEnabled=!0;v=a.isLegendEnabled&&v===v?c.getColorByValue(v)&&"#"+c.getColorByValue(v)||ba(c.rangeOutsideColor):void 0;b.isLeaf(p)?g.fill=w||v||d:(b=(b=(u?u:b).cssConf)&&b.fill,g.fill=w||(v?v:b));g.stroke=l?a.navigationBarBorderColor:a.plotBorderColor;g.strokeWidth=l?a.navigationBarBorderThickness:a.plotBorderThickness;g["stroke-dasharray"]=
"none";!l&&q&&"--"===q["stroke-dasharray"]&&(g["stroke-dasharray"]=q["stroke-dasharray"],g.strokeWidth=q.strokeWidth);return g}};a.abstractEventRegisterer=function(c,b,g,n){function f(a){var c={},b,d;for(b in x)d=x[b],c[d]=a[b];return c}var p=b.chart,l=p.components,q=l.dataset[0],w=l.toolbarBtns,u=p.chartInstance,v=b.conf,e=l.gradientLegend,h=c.drawTree,B=n.disposeChild,C,G=p.getJobList(),X=arguments,R,A,x={colorValue:"svalue",label:"name",value:"value",rect:"metrics"};R=a.context.getInstance("ClickedState");
p._intSR={};p._intSR.backToParent=C=function(c){var b=this,d=b,e=d&&b.getParent(),l=a.context.getInstance("ClickedState").get("VisibileRoot")||{};p.config.trackerConfig.length=0;G.trackerDrawID.push(fa.addJob(q.kdTreePartioning,q,[],J.priorityList.tracker));c?z("beforedrillup",{node:b,withoutHead:!v.showParent},u,void 0,function(){e&&(l.state="drillup",l.node=[{virginNode:a.getVisibleRoot()},e],B(d),h.apply(e,X));z("drillup",{node:b,withoutHead:!v.showParent,drillUp:C,drillUpToTop:A},u);b=b&&b.getParent()},
function(){z("drillupcancelled",{node:b,withoutHead:!v.showParent},u)}):(e&&(l.state="drillup",l.node=[{virginNode:a.getVisibleRoot()},e],B(d),h.apply(e,X)),b=b&&b.getParent())};p._intSR.resetTree=A=function(b){var c=this,d=c&&c.getParent(),e,l=a.context.getInstance("ClickedState").get("VisibileRoot")||{};p.config.trackerConfig.length=0;for(G.trackerDrawID.push(fa.addJob(q.kdTreePartioning,q,[],J.priorityList.tracker));d;)e=d,d=d.getParent();b?z("beforedrillup",{node:c,withoutHead:!v.showParent},
u,void 0,function(){e&&(l.state="drillup",l.node=[{virginNode:a.getVisibleRoot()},e],B(e),h.apply(e,X),z("drillup",{node:c,sender:p.fusionCharts,withoutHead:!v.showParent,drillUp:C,drillUpToTop:A},u))},function(){z("drillupcancelled",{node:c,withoutHead:!v.showParent},u)}):e&&(l.state="drillup",l.node=[{virginNode:a.getVisibleRoot()},e],B(e),h.apply(e,X))};return{click:function(a,b){var h=a.virginNode,l=q.graphics.singleTracker,g=q.kdTree,k,t,G;z("dataplotclick",f(a.virginNode),u);if(t=h.getParent()){if(h===
b)G=t,g&&(g.length=0),p.config.trackerConfig.length=0,k="drillup";else{if(h.next)G=h,g&&(g.length=0);else if(G=t,b===G){k=void 0;return}p.config.trackerConfig.length=0;k="drilldown"}e&&e.enabled&&e.resetLegend();c.applyShadeFiltering.reset();k&&z("before"+k,{node:G,withoutHead:!v.showParent},u,void 0,function(){R.set("VisibileRoot",{node:a,state:k});B.call(n,G);r=G;d.draw();z(k,{node:G,withoutHead:!v.showParent,drillUp:C,drillUpToTop:A},u)},function(){z(k+"cancelled",{node:G,withoutHead:!v.showParent},
u)});w.back&&w.back.attachEventHandlers({click:C.bind(G)});w.home&&w.home.attachEventHandlers({click:A.bind(G)});l&&l.attr({x:0,y:0,width:0,height:0,stroke:"rgba(255,255,255,0)"})}},mouseover:function(a){var b=f(a.virginNode);z("dataplotrollover",b,u,void 0,void 0,function(){z("dataplotrollovercancelled",b,u)})},mouseout:function(a){var b=f(a.virginNode),c=q.graphics.singleTracker;c&&c.attr({x:0,y:0,width:0,height:0,stroke:"rgba(255,255,255,0)"});z("dataplotrollout",f(a.virginNode),u,void 0,void 0,
function(){z("dataplotrolloutcancelled",b,u)})}}};a.setMaxDepth=function(a){return p=a};a.getVisibleRoot=function(){return r};a.setVisibleRoot=function(a){r=a};a.visibilityController=b;return a};ka=function(a,b){function d(){A.apply(this,arguments)}function c(b,c,f){k=new d(b,n,c);b=k.get();!1!==f&&(t=b);a.setVisibleRoot(b);return b}function g(){var c=r[m],d;b.realTimeUpdate=p.apply(this,arguments);d=Array.prototype.slice.call(arguments,0);d.unshift(c);c.drawTree.apply(a.getVisibleRoot(),d)}function p(){var a,
b,c=r[m];b=Array.prototype.slice.call(arguments,0);b.unshift(c);a=b.slice(-1)[0];return function(){var d=Array.prototype.slice.call(arguments,0),f=d.shift(),e=d.shift();ha(t,function(a){c.drawTree.apply(a||t,b)},a,f)[e].apply(this,d)}}var r,A=a.AbstractTreeMaker,m,k,t,n,f,x;r={sliceanddice:{areaBaseCalculator:function(a,b){return function(c,d,f){var e,h,B={},g,n,k,p=e=0;if(c){f&&(e=f.textMargin||e);p=e;f=c.getParent();e=c.getSibling("left");if(f){h=f.getValue();k=f.rect;g=k.height-2*b-p;n=k.width-
2*a;B.effectiveRect={height:g,width:n,x:k.x+a,y:k.y+b+p};B.effectiveArea=g*n;B.ratio=c.getValue()/h;if(e)return d.call(c,B,e,f);B.lastIsParent=!0;return d.call(c,B,f)}return null}}},applyShadeFiltering:function(a,b,c){a.setRangeOutEffect(b,c);this.applyShadeFiltering.reset=function(){a.resetPointers()};return function(b){a.moveLowerShadePointer(b.start);a.moveHigherShadePointer(b.end)}},alternateModeManager:function(){return function(a,b){var c,d,f,e,h,B=a.effectiveArea*a.ratio;d=a.effectiveRect;
var g=b.rect;a.lastIsParent?(e=d.x,h=d.y,c=d.height,d=d.width,f=this.isDirectionVertical=!0):(c=d.height+d.y-(g.height+g.y),d=d.width+d.x-(g.width+g.x),f=this.isDirectionVertical=!b.isDirectionVertical);f?(d=B/c,e=void 0!==e?e:g.x,h=void 0!==h?h:g.y+g.height):(c=B/d,e=void 0!==e?e:g.x+g.width,h=void 0!==h?h:g.y);return{height:c,width:d,x:e,y:h}}},horizontalVerticalManager:function(a){var b="vertical"===a?!0:!1;return function(a,c,d){var e,h,f,l=a.effectiveArea*a.ratio,g=a.effectiveRect,k=c.rect;a.lastIsParent?
(h=g.x,f=g.y,a=g.height,e=g.width,c=this.isDirectionVertical=!c.isDirectionVertical):(a=g.height+g.y-(k.height+k.y),e=g.width+g.x-(k.width+k.x),c=this.isDirectionVertical=!d.isDirectionVertical);(c=b?c:!c)?(0===a&&(a=g.height,h=void 0!==h?h:k.x+k.width,f=void 0!==f?f:k.y),e=l/a,h=void 0!==h?h:k.x,f=void 0!==f?f:k.y+k.height):(0===e&&(e=g.width,h=void 0!==h?h:k.x,f=void 0!==f?f:k.y+k.height),a=l/e,h=void 0!==h?h:k.x+k.width,f=void 0!==f?f:k.y);return{height:a,width:e,x:h,y:f}}},drawTree:function(b,
c,d,g){var k=c.chart,e=k.components,h=k.config||(k.config={}),B=h.trackerConfig||(h.trackerConfig=[]),n=e.numberFormatter,e=e.toolbarBtns,p=g.drawRect,t=g.drawText,r=g.drawHot,h=d.horizontalPadding,m=d.verticalPadding,A=c.chart.linkedItems.smartLabel,y=a.iterator,E=y(this).df,H,F=b.areaBaseCalculator(h,m),D=c.conf,K=D.highlightParentsOnHover,S,z=a.context,h=a.visibilityController,N=a.mapColorManager(D,c.conf.colorRange),m=a.abstractEventRegisterer.apply(a,arguments),T=m.click,ia=m.mouseover,L=m.mouseout,
m=D.slicingMode,M=b["alternate"===m?"alternateModeManager":"horizontalVerticalManager"](m),m=k._intSR,I,y=z.getInstance("ClickedState").get("VisibileRoot")||{};(I=y.node)&&y.state&&("drillup"===y.state.toLowerCase()?I instanceof Array?h.controlPreAnimVisibility(I[0].virginNode,I[1]):h.controlPreAnimVisibility(I.virginNode):h.displayAll(y.node.virginNode));S=a.initConfigurationForlabel({x:5,y:5},D.parentLabelLineHeight,D);for(h=H=E.next(x=a.setMaxDepth(this.getDepth()+f));h.getParent();)h=h.getParent();
D.showNavigationBar?(e.home.hide(),e.back.hide()):h!=H?(e.home.show(),e.back.show()):(e.home.hide(),e.back.hide());A.useEllipsesOnOverflow(k.config.useEllipsesWhenOverflow);A.setStyle(D._setStyle={fontSize:(D.labelFontSize||D.baseFontSize)+"px",fontFamily:D.labelFont||D.baseFont,lineHeight:1.2*(D.labelFontSize||D.baseFontSize)+"px"});k=m.backToParent;h=m.resetTree;e.back&&e.back.attachEventHandlers({click:k.bind(H)});e.home&&e.home.attachEventHandlers({click:h.bind(H)});(function U(a,b){var c,d,e,
h,f,l,q,k;l={};var w,v,m={},y={};q={};var aa="",W,I;a&&(W=n.yAxis(a.getValue()),I=n.sYAxis(a.getColorValue()),a.setPath(),c=a.rect||{},d=a.textRect||{},e=a.rect={},q=a.textRect={},e.width=b.width,e.height=b.height,e.x=b.x,e.y=b.y,q=N(a),(v=a.plotItem)&&g.graphicPool(!0,"plotItem",v,c),v=a.plotItem=p(e,q,c,a.overAttr),a.cssConf=q,k=S(a,e),h=k.conf,l.textMargin=h.rectShiftY,q=a.textRect=h.textRect,w=A.getSmartText(h.label,q.width,q.height).text,a.plotItem=v,(h=a.labelItem)?(f=a.highlightItem,g.graphicPool(!0,
"labelItem",h,c),g.graphicPool(!0,"highlightItem",f,c)):d=d||{},d=t(w,q,{textAttrs:k.attr,highlightAttrs:k.highlight},d,a.overAttr),a.labelItem=d.label,a.highlightItem=d.highlightMask,m.virginNode=a,m.plotItem=v,m.textItem=d,m.virginNode.dirtyNode=m,a.getColorValue()&&(aa=D.tooltipSeparationCharacter+I),m.toolText=D.showTooltip?J.parseTooltext(D.plotToolText,[1,2,3,119,122],{label:a.getLabel(),formattedValue:W,formattedsValue:I},{value:a.getValue(),svalue:a.getColorValue()})||a.getLabel()+D.tooltipSeparationCharacter+
W+aa:ea,m.rect=e,y.hover=[function(a){var c,b,d;d=z.getInstance("hover");b=this.virginNode;c=K&&!b.next?(c=b.getParent())?c:b:this.virginNode;d.set("element",c);d=da(qa(c.cssConf.fill,80),60);a.attr({fill:d});ia(this)}.bind(m),function(){var a,c;a=z.getInstance("hover").get("element");c=da(a.cssConf.fill||"#fff",0);a.plotItem.tracker.attr({fill:c});L(this)}.bind(m)],y.tooltip=[m.toolText],y.click=[function(){T(this,H)}.bind(m)],(e=a.hotItem)&&g.graphicPool(!0,"hotItem",e,c),B.push({node:a,key:"hotItem",
plotDetails:m,evtFns:y,callback:r}),c=E.next(x),l=F(c,M,l),U(c,l))})(H,d)}},squarified:{orderNodes:function(){return this.sort(function(a,c){return parseFloat(a.value,10)<parseFloat(c.value,10)?1:-1})},areaBaseCalculator:function(a,c){return function(b,d,f){var e={},h,g=h=0,k,m;if(b&&0!==b.length)return f&&(h=f.textMargin||h),g=h,k=b[0],(b=k.getParent())?(m=b.rect,f=m.height-2*c-g,h=m.width-2*a,e.effectiveRect={height:f,width:h,x:m.x+a,y:m.y+c+g},e.effectiveArea=f*h,d.call(k,e,b)):null}},layoutManager:function(){function a(c,
b){this.totalValue=b;this._rHeight=c.height;this._rWidth=c.width;this._rx=c.x;this._ry=c.y;this._rTotalArea=c.height*c.width;this.nodes=[];this._prevAR=void 0;this._rHeight<this._rWidth&&(this._hSegmented=!0)}a.prototype.constructor=a;a.prototype.addNode=function(a){var c=this._rTotalArea,b,d,e,h,f,g,l,k=this._hSegmented,m=this._rx,n=this._ry,p,t,r,A,x=0;this.nodes.push(a);e=0;for(d=this.nodes.length;e<d;e++)x+=parseFloat(this.nodes[e].getValue(),10);b=x/this.totalValue*c;k?(c=this._rHeight,d=b/c,
p=m+d,t=n,r=this._rHeight,A=this._rWidth-d):(d=this._rWidth,c=b/d,p=m,t=n+c,r=this._rHeight-c,A=this._rWidth);e=0;for(h=this.nodes.length;e<h;e++)a=this.nodes[e],f=a.getValue(),g=f/x*b,a.hRect=a.rect||{},a._hRect=a._rect||{},f=a.rect={},k?(f.width=l=d,f.height=l=g/l,f.x=m,f.y=n,n+=l):(f.height=l=c,f.width=l=g/l,f.x=m,f.y=n,m+=l),g=Y(f.height,f.width),f=na(f.height,f.width),a.aspectRatio=g/f;if(1<this.nodes.length){if(this.prevAR<a.aspectRatio){this.nodes.pop().rect={};e=0;for(d=this.nodes.length;e<
d;e++)this.nodes[e].rect=1===d&&this.nodes[e].firstPassed?this.nodes[e]._hRect:this.nodes[e].hRect,k=this.nodes[e]._rect={},m=this.nodes[e].rect,k.width=m.width,k.height=m.height,k.x=m.x,k.y=m.y;return!1}}else a&&(k=a._rect={},m=a.rect,k.width=m.width,k.height=m.height,k.x=m.x,k.y=m.y,a.firstPassed=!0);this.prevAR=a.aspectRatio;this.height=c;this.width=d;this.getNextLogicalDivision=function(){return{height:r,width:A,x:p,y:t}};return a};return{RowLayout:a}}(),applyShadeFiltering:function(a,c,b){a.setRangeOutEffect(c,
b);this.applyShadeFiltering.reset=function(){a.resetPointers()};return function(c){a.moveLowerShadePointer(c.start);a.moveHigherShadePointer(c.end)}},drawTree:function(c,b,d,g){var k=b.chart,e=k.config||(k.config={}),h=e.trackerConfig||(e.trackerConfig=[]),e=k.components,m=e.numberFormatter,e=e.toolbarBtns,n=c.areaBaseCalculator(d.horizontalPadding,d.verticalPadding),p=c.layoutManager.RowLayout,t=b.chart.linkedItems.smartLabel,r=g.drawRect,A=g.drawText,y=g.drawHot,z=a.iterator,E=z(this).bf,H,F=b.conf,
D=F.highlightParentsOnHover,K,S=a.context,P=a.mapColorManager(F,b.conf.colorRange),z=a.abstractEventRegisterer.apply(a,arguments),N=z.click,T=z.mouseover,ia=z.mouseout,z=k._intSR,L=a.visibilityController,M,I;M=S.getInstance("ClickedState").get("VisibileRoot")||{};(I=M.node)&&M.state&&("drillup"===M.state.toLowerCase()?I instanceof Array?L.controlPreAnimVisibility(I[0].virginNode,I[1]):L.controlPreAnimVisibility(I.virginNode):L.displayAll(M.node.virginNode));K=a.initConfigurationForlabel({x:5,y:5},
F.parentLabelLineHeight,F);for(E=H=E.next(x=a.setMaxDepth(this.getDepth()+f));E.getParent();)E=E.getParent();F.showNavigationBar?(e.home.hide(),e.back.hide()):E!=H?(e.home.show(),e.back.show()):(e.home.hide(),e.back.hide());t.useEllipsesOnOverflow(k.config.useEllipsesWhenOverflow);t.setStyle(F._setStyle={fontSize:(F.labelFontSize||F.baseFontSize)+"px",fontFamily:F.labelFont||F.baseFont,lineHeight:1.2*(F.labelFontSize||F.baseFontSize)+"px"});k=z.backToParent;z=z.resetTree;e.back&&e.back.attachEventHandlers({click:k.bind(H)});
e.home&&e.home.attachEventHandlers({click:z.bind(H)});(function U(a,c){var b,d={},e,f,k,l,q,w,v=0,z,E,I,L;w={};var M;z={};E={};l={};var V="",W,O;if(a){W=m.yAxis(a.getValue());O=m.sYAxis(a.getColorValue());a.setPath();if(b=a.__initRect)d.x=b.x,d.y=b.y,d.width=b.width,d.height=b.height;k=a.textRect||{};b=a.rect=a.__initRect={};l=a.textRect={};b.width=c.width;b.height=c.height;b.x=c.x;b.y=c.y;l=P(a);(I=a.plotItem)&&g.graphicPool(!0,"plotItem",I,d);I=a.plotItem=r(b,l,d,a.overAttr);a.cssConf=l;M=K(a,b);
e=M.conf;w.textMargin=e.rectShiftY;l=a.textRect=e.textRect;L=t.getSmartText(e.label,l.width,l.height).text;(f=a.labelItem)?(e=a.highlightItem,g.graphicPool(!0,"labelItem",f,d),g.graphicPool(!0,"highlightItem",e,d)):k=k||{};k=A(L,l,{textAttrs:M.attr,highlightAttrs:M.highlight},k,a.overAttr);a.labelItem=k.label;a.highlightItem=k.highlightMask;a.plotItem=I;z.virginNode=a;z.plotItem=I;z.textItem=k;z.virginNode.dirtyNode=z;a.getColorValue()&&(V=F.tooltipSeparationCharacter+O);z.toolText=F.showTooltip?
J.parseTooltext(F.plotToolText,[1,2,3,119,122],{label:a.getLabel(),formattedValue:W,formattedsValue:O},{value:a.getValue(),svalue:a.getColorValue()})||a.getLabel()+F.tooltipSeparationCharacter+W+V:ea;z.rect=b;E.hover=[function(a){var c,b,d;d=S.getInstance("hover");b=this.virginNode;c=D&&!b.next?(c=b.getParent())?c:b:this.virginNode;d.set("element",c);d=c.cssConf;d=da(d.fill&&qa(d.fill,80),60);a.attr({fill:d});T(this)}.bind(z),function(a){var c;c=S.getInstance("hover").get("element").cssConf;c=da(c.fill||
"#fff",0);a.attr({fill:c});ia(this)}.bind(z)];E.tooltip=[z.toolText];E.click=[function(){N(this,H)}.bind(z)];(b=a.hotItem)&&g.graphicPool(!0,"hotItem",b,d);h.push({node:a,key:"hotItem",plotDetails:z,evtFns:E,callback:y});if(q=void 0!==x?a.getDepth()>=x?void 0:a.getChildren():a.getChildren())for(z=n(q,function(a,c){var b,d,e=0,h,f,g=[];b=new p({width:a.effectiveRect.width,height:a.effectiveRect.height,x:a.effectiveRect.x,y:a.effectiveRect.y},c.getValue());for(d=q.length;e++!==d;)h=q[e-1],f=b.addNode(h),
!1===f?(b=b.getNextLogicalDivision(),b=new p(b,c.getValue()-v),e--):(v+=parseFloat(h.getValue(),10),g.push(h));return g},w),d=0,w=z.length;d<w;d++)E=z[d],U(E,E.rect)}})(H,d)}}};d.prototype=Object.create(A.prototype);d.prototype.constructor=A;d.prototype.order=function(a){var c=r[m],b=c.orderNodes;return b?b.apply(a,[c]):a};b.init=function(c,b,d){m=c;n=b;f=a.setMaxDepth(d);return r[m]};b.plotOnCanvas=function(a,b,d){t=c(a,d);return g};b.applyShadeFiltering=function(a,c){var b,d;d=r[m].applyShadeFiltering(k.getBucket(),
a,c);return function(a){b=Array.prototype.slice.call(arguments,0);b.unshift(a);d.apply(k.getBucket(),b)}};b.setTreeBase=function(a){return a&&(t=a)};b.realTimeUpdate=p;b.makeTree=c;return b};ha=function(a,b,d,c){function g(c){var b,d=0;b=a;if(!c.length)return a;for(;b;){b=p.call(b,c[d]);if(d===c.length-1&&b)return r=b.getValue(),b;d+=1}}function p(a){var c,b,d,g=this.getChildren()||[],f=g.length;for(c=0;c<f;c+=1)if(d=g[c],d.label.toLowerCase().trim()===a.toLowerCase().trim()){b=d;break}return b}var r;
return{deleteData:function(a,c){var k=g(a),p=(void 0).iterator(k).df,n=k&&k.getParent(),f=k&&k.getSiblingCount("left"),x=n&&n.getChildren(),l=(void 0).getVisibleRoot();if(k&&n){x.splice(f,1);for(k===l&&(l=k.getParent()||l);k;)d.disposeItems(k),k=p.next();for(;n;)n.setValue(-r,!0),n=n.getParent();c&&b(l)}},addData:function(a,d,k,p){for(var n,f,r,l=0,q=!0,w=(void 0).getVisibleRoot();a.length;)if(n=a.pop(),n=(void 0).makeTree(n,c,!1),l=n.getValue(),f=g(d||[]))for(f.getChildren()||(r=f.getValue(),q=!1),
f.addChildren(n,p);f;)f.setValue(l,q),r&&(l-=r,r=void 0,q=!0),f=f.getParent();k&&b(w)}}};la=function(a,b,d){function c(){}function g(c){var b=t.plotBorderThickness;m.apply(a.getVisibleRoot(),[x,{width:c.effectiveWidth,height:c.effectiveHeight,x:c.startX,y:c.startY,horizontalPadding:t.horizontalPadding,verticalPadding:t.verticalPadding},n]);t.plotBorderThickness=b}function p(a,c,b){var d=a.width,f=a.height,g=t.seperatorAngle/2;a=["M",a.x,a.y];var k=y(g?f/2*(1-sa(g)):b,15);b=function(a){return{both:["h",
d,"v",a,"h",-d,"v",-a],right:["h",d,"v",a,"h",-d,"l",k,-a/2,"l",-k,-a/2],no:["h",d,"l",k,a/2,"l",-k,a/2,"h",-d,"l",k,-a/2,"l",-k,-a/2],left:["h",d,"l",k,a/2,"l",-k,a/2,"h",-d,"v",-a]}};return{path:a.concat(b(f)[c]),_path:a.concat(b(0)[c]),offset:k}}function r(){var a=Array.prototype.splice.call(arguments,0);a.push(!0);l("navigationBar").apply(this,a)}var x,m,k,t,n,f,z=function(c,b){var f,g,l=a.mapColorManager(t,t.colorRange,!0),m=function(){var a;return{get:function(c,b,d){var e={y:c.startY,height:c.effectiveHeight};
b=f[b];var h=b.getParent();e.x=a||(a=c.startX);a=d?a+(e.width=c.effectiveWidth*(b.getValue()/h.getValue())):a+(e.width=c.effectiveWidth/g);return e},resetAllocation:function(){a=void 0}}}(),r=a.initConfigurationForlabel({x:5,y:5},t.parentLabelLineHeight,t),v=n.drawPolyPath,w=n.drawText,z=n.drawHot,y={navigationHistory:{path:"polyPathItem",label:"pathlabelItem",highlightItem:"pathhighlightItem",hotItem:"pathhotItem"}},H=x.chart,F=H.config.trackerConfig,D=H.components.gradientLegend,H=H.linkedItems.smartLabel,
J=function(c){return function(){var b=a.context.getInstance("ClickedState").get("VisibileRoot")||{};F.length=0;b.state="drillup";b.node=[{virginNode:a.getVisibleRoot()},c];D&&D.enabled&&D.resetLegend();d.draw([c,c,c])}},K=function(){return function(){}},Q=function(){return function(){}},N,T,O,L,M,I,P=t._setStyle,U;N=q.get().navigationBar;L=2*u("navigationBar");P=na(N*k.effectiveHeight-(L+6),P.fontSize.replace(/\D+/g,""));N=P+"px";y.stacked={path:"stacked"+y.navigationHistory.path,label:"stacked"+
y.navigationHistory.label,highlightItem:"stacked"+y.navigationHistory.highlightItem,hotItem:"stacked"+y.navigationHistory.hotItem};m.resetAllocation();(function(c){var b=a.getVisibleRoot();f=c?b.getChildren():b.getPath()||[].concat(b);f.pop();g=f.length})(b);H.setStyle({fontSize:N,lineHeight:N});for(N=0;N<g;N+=1)L=f[N],M=m.get(c,N,b),T=(O=p(M,b?"both":1===g?"both":0===N?"left":N<g-1?"no":"right")).offset,L[y[b?"stacked":"navigationHistory"].path]=v(O,l(L,!0,!0),N),O=r(L,M,!1,!0),I=O.conf,U=I.textRect,
U.width-=2*T,U.y=M.y+M.height/2,T=H.getSmartText(I.label,U.width,Y(P,U.height)).text,T=w(T,U,{textAttrs:O.attr,highlightAttrs:O.highlight},{y:M.height/10,"font-size":t._setStyle.fontSize,"font-family":t._setStyle.fontFamily},(b?"stacked":"")+"path"),L[y[b?"stacked":"navigationHistory"].label]=T.label,L[y[b?"stacked":"navigationHistory"].highlightItem]=T.highlightMask,F.push({node:L,key:y[b?"stacked":"navigationHistory"].hotItem,plotDetails:{rect:M},evtFns:{click:[J(L,b)],hover:[K(L),Q()],tooltip:[t.showTooltip?
L.getLabel():ea]},callback:z})},l=function(a){return{treeMap:g,navigationBar:z,stackedNavigation:r}[a]},q=function(){var a={treeMap:1,navigationBar:0,stackedNavigation:0};return{set:function(c){var b=y(t.navigationBarHeightRatio,t.navigationBarHeight/k.effectiveHeight,.15),d=t.labelFontSize?Y(t.labelFontSize,t.baseFontSize):t.baseFontSize,f=2*u("navigationBar"),b=Y((6+d+f)/k.effectiveHeight,b);.1>b?b=.1:.15<b&&(b=.15);t.navigationBarHeightRatio=b;a=c?{treeMap:1-b,navigationBar:b,stackedNavigation:0}:
{treeMap:1,navigationBar:0,stackedNavigation:0}},get:function(){return a}}}(),w=0,u=function(a){var b=t.plotBorderThickness,c=t.navigationBarBorderThickness;return t.verticalPadding+("navigationBar"===a?c:b)},v=function(a){var b=k.effectiveWidth,c=k.effectiveHeight,d=u(a);a=q.get()[a];1<=w&&(w=0);w+=a;return{effectiveHeight:ma(a*c*100)/100-d,effectiveWidth:b,startX:k.startX,startY:k.startY+d+ma((w-a)*c*100)/100}};c.prototype.constructor=c;c.prototype.init=function(a,b){(this.conf||(this.conf={})).name=
a.name;this.setDrawingArea(a.drawingAreaMeasurement);this.draw=this.draw(b)};c.prototype.setDrawingArea=function(a){this.conf.drawingAreaMeasurement=a};c.prototype.draw=function(a){return function(){var b=this.conf;0<b.drawingAreaMeasurement.effectiveHeight&&a(b.drawingAreaMeasurement)}};c.prototype.eventCallback=function(){};f=function(){var a=[];return{get:function(){return a},set:function(b){var d;b?(d=new c,d.init({name:b.type,drawingAreaMeasurement:b.drawingArea},b.drawFn),a.push(d)):a.length=
0;return a}}}();d.init=function(){var a,b=["navigationBar","treeMap","stackedNavigation"];a=Array.prototype.slice.call(arguments,0);x=a[0];k=a[1];t=x.conf;n=a[2];m=a[4];for(f.get().length>=b.length&&f.set();b.length;)a=b.shift(),f.set({type:a,drawFn:l(a),drawingArea:v(a)})};d.draw=function(b){var c,g,k;c=a.getVisibleRoot();n.disposeChild(c);b&&(c=b[1]);c.getParent()?t.showNavigationBar&&d.heightProportion.set(!0):d.heightProportion.set(!1);g=f.get();for(c=0;c<g.length;c+=1)k=g[c],k.setDrawingArea(v(k.conf.name)),
b&&a.setVisibleRoot(b[c]),k.draw()};d.heightProportion=q;d.remove=function(){var b=a.getVisibleRoot();b&&n.disposeChild(b)};return d}}])});
